rapid7/recog

xml/ftp_banners.xml, xml/sip_banners.xml, xml/snmp_sysdescr.xml
This work is related to this task: CONTENT-6924
recog_verify.rb tests pass for all 3 edited files.
Nexpose DTest passing as well.
=> Adding new Cisco TelePresence banners

.travis.yml, features/match.feature
These were not running as part of travis and one of the test was broken.  I've fixed the broken test and enabled cucumber by default.
=> Fix and enable cucumber tests by default

xml/http_wwwauth.xml
Adds a few that should be ignored as they are too generic along with several I've encountered in the wild.
=> Add various WWW-Authenticate fingerprints

xml/ssh_banners.xml
added Comware SSH banner and successfully tested in Nexpose
=> Add Comware SSH banner

bin/recog_match, xml/ftp_banners.xml
=> Correct generic AIX / HP-UX FTP fingerprint

xml/ssh_banners.xml
=> Improve some SSH fingerprints

xml/ftp_banners.xml
=> Add and improve FTP fingerprints

xml/ftp_banners.xml
Tested as follows:
```
thart@AUS-T3500-0825:~/nexpose/recog$ rake test
rake aborted!
Don't know how to build task 'test'
(See full trace by running task with --trace)
thart@AUS-T3500-0825:~/nexpose/recog$ vim .travis.yml 
thart@AUS-T3500-0825:~/nexpose/recog$ travis
travis: command not found
thart@AUS-T3500-0825:~/nexpose/recog$ bundle exec rake tests
/home/thart/.rvm/rubies/ruby-2.2.0/bin/ruby -I/home/thart/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.3.2/lib:/home/thart/.rvm/gems/ruby-2.2.0/gems/rspec-support-3.3.0/lib /home/thart/.rvm/gems/ruby-2.2.0/gems/rspec-core-3.3.2/exe/rspec --pattern spec/\*\*/\*_spec.rb
/home/thart/.rvm/gems/ruby-2.2.0/gems/regexp_parser-0.2.1/lib/regexp_parser/scanner.rb:2249: warning: mismatched indentations at 'end' with 'begin' at 1713 …
```
=> Add FTP banner for FTP server of the ProRat malware

misc/convert_mysql_err, xml/mysql_error.xml
AFAIK this data is currently unused, but it fixes #66 regardless.
=> Add remaining MySQL error messages

xml/ntp_banners.xml, xml/snmp_sysdescr.xml
DCA-10
* Added SNMP fingerprints for 10.3 -> 10.10
=> SNMP fingerprints for Mac OS X

xml/http_servers.xml, xml/smb_native_os.xml
* Added banner fingerprint for 10.3 using QuickTime Stream Server.
* Added banner fingerprint for 10.5 and 10.6 using Samba
=> New fingerprints for OS X

bin/recog_verify, features/data/tests_with_failures.xml, features/verify.feature, lib/recog/fingerprint.rb, lib/recog/match_reporter.rb, lib/recog/verifier.rb, lib/recog/verify_reporter.rb, spec/lib/recog/match_reporter_spec.rb, spec/lib/recog/verify_reporter_spec.rb
This fixes @jkennedy-r7's #90.
=> Update recog_verify to catch invalid params, be more useful

xml/snmp_sysdescr.xml
I found these banners on Shodan.
=> SNMP fingerprints for ScreenOS

xml/http_servers.xml
* Added fingerprint for JBoss EAP
*  Fixed Regex for JBoss AS
=> Banner fingerprint for JBoss EAP

xml/ssh_banners.xml
Second pass at adding more SSH banners
=> Add missing ssh banners

xml/mysql_banners.xml
=> Add mariadb enterprise edition fingerprint

xml/pop_banners.xml
An attempt by an intern to contribute to Recog
=> Edits to pop_banners.xml

.travis.yml
This is intended to fix #139, though obviously this problem will happen again as Ruby advances and this file ages, so we should update this every so often.
=> Update ruby versions for travis CI

xml/mysql_banners.xml
=> Add fingerprint for MariaDB on Ubuntu 16.04

xml/mysql_banners.xml
Address Issue #156 by improving an existing match's support for 10.x version banners.
=> Improve MariaDB on Ubuntu - Issue #156

xml/ftp_banners.xml
Changing incorrect use of hw.device to be hw.product instead.  Correcting Firewall-1 OS from 'Firewall-1' to 'Gaia OS'
=> FTP: tweak hw.device usage, fix Firewall-1 OS

xml/nntp_banners.xml
This improves coverage of NNTP server banners.  I updated these based on recent Sonar nntp and nntps studies and added coverage for several that feature prominently in those results.
=> Improve NNTP fingerprints

xml/ssh_banners.xml, xml/telnet_banners.xml, xml/upnp_banners.xml
This isn't done automatically as part of our current processes so we need to do it periodically instead.
=> Update CPEs for SSH, telnet and UPnP

xml/telnet_banners.xml
Quick PR to add attributes that I had missed during my previous PR to the Cisco and Microsoft telnet regex's.
Running **rake tests** within recog and running **bin/recog_verify xml/telnet_banners.xml** within recog
=> Addition of attributes for Cisco and Windows fingerprints

xml/mdns_device-info_txt.xml, xml/telnet_banners.xml
While working on a pile of PRs for recog, I encountered some minor formatting issues.  I've decided to address these issues all at once rather than whenever I get around to PR'ing the other PRs.
Cleanup.
`bundle exec rspec` passes, and tests the fingerprint files extensively.
=> Minor XML format cleanup

xml/sip_banners.xml, xml/sip_user_agents.xml, xml/snmp_sysdescr.xml
This adds some additional fingerprinting for a variety of SIP devices as taken from recent Sonar SIP studies.
GPRs, new tests pass.
=> Improve SIP fingerprinting

lib/recog/version.rb, xml/dns_versionbind.xml, xml/upnp_banners.xml
This adds a variety of new UPnP fingerprints is outlined in the individual commits.
More fingerprints.
Examples for everything tested with GPRs.
=> Improve UPnP Server fingerprinting

xml/http_servers.xml
This improves HTTP Server fingerprinting in a variety of ways based on recent Sonar HTTP studies. The specifics can be seen in the individual commits.
More fingerprints.
GPRs, local `bundle exec rspec` passes.
=> Improve HTTP Server fingerprinting

spec/lib/fingerprint_self_test_spec.rb, xml/apache_os.xml, xml/dns_versionbind.xml, xml/ftp_banners.xml, xml/http_servers.xml, xml/http_wwwauth.xml, xml/imap_banners.xml, xml/nntp_banners.xml, xml/ntp_banners.xml, xml/pop_banners.xml, xml/rsh_resp.xml, xml/smb_native_lm.xml, xml/smtp_banners.xml, xml/smtp_debug.xml, xml/smtp_ehlo.xml, xml/smtp_expn.xml, xml/smtp_help.xml, xml/smtp_noop.xml, xml/smtp_quit.xml, xml/smtp_rset.xml, xml/smtp_turn.xml, xml/smtp_vrfy.xml, xml/snmp_sysdescr.xml, xml/snmp_sysobjid.xml, xml/ssh_banners.xml, xml/telnet_banners.xml, xml/upnp_banners.xml
These provided no value and devalues all of the others that are already here and more specific.  In some cases where there was a more obvious value, I put one in, but there is almost certainly more/related cleanup that _could_ be done.
Quality
GPRs, new test.
=> Enforce that no fingerprint value can be General/Unknown, and update all offenders

xml/http_cookies.xml, xml/http_servers.xml, xml/http_wwwauth.xml, xml/telnet_banners.xml
Various improvements and additions to (mostly) HTTP fingerprints. 
Examples, `bundle exec rspec` passes
=> Improve HTTP fingerprints for more cameras, AirTunes, DVRs, Splunk, Oracle XML DB, more

xml/ftp_banners.xml, xml/http_servers.xml, xml/http_wwwauth.xml, xml/mysql_banners.xml, xml/sip_user_agents.xml, xml/snmp_sysdescr.xml, xml/telnet_banners.xml, xml/upnp_banners.xml
A variety of improvements that started with FTP in general and ended up with a few related cleanups.  
More fingerprints for QNAP, Axis, improving Pure and Pro-ftpd fingerprints, Netgear ReadyNAS and more.  I also made Camera more consistent with the `Web camera` used elsewhere.  Eventually we'll standardize on one, but for now we stay consistent.  
New examples, GPRs.
=> Improve FTP and SIP fingerprinting of network cameras, etc

xml/sip_user_agents.xml
Add fingerprint 
More FPs
Rspec
=> OCTO-1870 Add Nero SIP device

xml/dns_versionbind.xml, xml/http_wwwauth.xml, xml/ssh_banners.xml, xml/telnet_banners.xml, xml/upnp_banners.xml
This started as another round of updates to SSH fingerprints but I made some related changes along the way. All of these came from recent Sonar studies.
More, better fingerprints..
Examples tested via GPRs.
=> Improve SSH fingerprints for VxWorks, Ruijie, Netscreen, Draytek, Paramiko, Rebex, Bitvise, more

xml/http_servers.xml
Right now in recog we can capture CUPS fingerprints for CUPS servers with the server field such as these:
```
CUPS/1.5
CUPS/1.4
CUPS/1.2
```
For example:
```
$ echo 'CUPS/1.5' | bin/recog_match xml/http_servers.xml -
MATCH: {"matched"=>"Server for the CUPS web interface.", "service.vendor"=>"Apple", "service.product"=>"CUPS", "service.family"=>"CUPS", "service.version"=>"1.5", "service.cpe23"=>"cpe:/a:apple:cups:1.5", "service.protocol"=>"http", "fingerprint_db"=>"http_header.server", "data"=>"CUPS/1.5"}
```
However another valid CUPS server field are these:
```
CUPS/2.0 IPP/2.1
CUPS/2.1 IPP/2.1
CUPS/2.2 IPP/2.1
CUPS/1.7 IPP/2.1
```
In these cases we have no match at all:
```
cam-mbp-5971:recog ssikdar$ echo 'CUPS/2.0 IPP/2.1' | bin/recog_match xml/http_servers.xml -
FAIL: CUPS/2.0 …
```
=> Add an additional CUPS fingerprint

xml/http_servers.xml, xml/upnp_banners.xml
This adds several new and improved fingerprints, summarized in the subject and individual commits.
More/better fingerprints!
New tests, all pass.
=> Add HTTP fingerprinting for Sonos, cPanel, Firefly/mt-daapd, Systech Payment Gateways, CentOS web panel

.travis.yml
Upgrade travis to include ruby versions 2.4.x and 2.5.x
2.3 is soon to be EOL so adding support makes sure recog works with current ruby versions
tested locally on rbenv but it travis so the build system iteself will be a test
- [ X] I have updated the documentation accordingly (not required).
- [ X] I have added tests to cover my changes (added and updated travis CI ruby envs).
- [ X ] All new and existing tests passed.
=> update travis for ruby 23 24 25 latest versions

xml/http_wwwauth.xml
I'm submitting this PR since I happened to have the data handy.  This PR only updates `xml/http_wwwauth.xml` and makes the following changes:
- Adds some missing examples
- Adds 1 fingerprint for SpeedTouch and reworks the WRT54G fingerprint to be more global
- Replaces the wildcard `.` with `&quot;` where appropriate in the regex
- Adds `hw.*` params in select cases where I was already touching a fingerprint.
- Moves `Fujitsu Siemens Primergy with BMC RemoteView on an iRMC card` lower in the file behind more frequently seen matches.
Improved ability test.
`rspec`
=> Add examples to http_wwwauth.xml

xml/ftp_banners.xml
A number of new patterns, as well as updating some others, to match a number of vxworks FTP banner messages. 
Finding more VxWorks Operating Systems.
Added examples.
Ran `rake test`.
=> Add patterns for vxworks FTP

.travis.yml
* Mark jruby target as allowed to fail (i.e. the overall build status will succeed regardless of jruby result).
* Use openjdk8 instead of system default to avoid jruby issues with openjdk11
Fix #238 
Check results of this pull request.
=> Attempt to fix and/or ignore JRuby test issues on Travis-CI

.gitignore, README.md, xml/smtp_banners.xml
This PR
- Adds an example to the new OpenSMTPd fingerprint (examples are required)
- Adds a missing Exim fingerprint
- Fixes some linting, spelling, etc errors in README.MD
- Adds a few entries to .gitignore
Cleanup
`rspec`, GPR hooks, testing against a dataset
=> Tweak SMTP banners, lint README

xml/html_title.xml
Additional HTML Title fingerprints
This PR adds more HTML Title fingerprints, improving coverage when HTML Titles are available.
recog_verify and respec, combined with real-world testing.
* Non-breaking updates to fingerprints
=> More HTML Title fingerprints

xml/sip_banners.xml
Update SIP fingerprints (new fingerprints and updates to existing definitions).
Improve SIP device fingerprinting
Real-world network scans, rspec, and recog_verify
Boring fingerprint updates
=> SIP fingerprint updates

xml/dns_versionbind.xml, xml/smtp_banners.xml, xml/telnet_banners.xml
- Two internet-connected power meters
- One new DOCSIS cable modem with flashed OS
- One new Richo printer detection
- CleanBrowsing, pi-hole dnsmasq, keweon and Quad9 DNS
Verified with:
```
bin/recog_verify xml/telnet_banners.xml
bin/recog_verify xml/dns_versionbind.xml
```
=> Four new Telnet fingerprints + Four new DNS fingerprints

xml/rtsp_servers.xml
This PR adds signatures for RTSP servers.
These signatures were created after building new studies in Sonar, giving us a large volume of RTSP banners to analyze.
These signatures were run through the results of an RTSP Sonar study. Passed recog_verify
- Non-breaking updates to fingerprints
=> RTSP Fingerprints Added

xml/rtsp_servers.xml
A quick PR to tweak some things after landing PR #253
Automated
=> Post #253 tweaks to RTSP fingerprints

xml/apache_os.xml, xml/ftp_banners.xml, xml/html_title.xml, xml/http_cookies.xml, xml/http_servers.xml, xml/http_wwwauth.xml, xml/sip_banners.xml, xml/sip_user_agents.xml, xml/snmp_sysdescr.xml, xml/ssh_banners.xml, xml/telnet_banners.xml, xml/x11_banners.xml, xml/x509_subjects.xml
This is a collection of fingerprint updates and cleanups encountered while testing Recog.
This PR improves the coverage and consistency of fingerprints.
Real-world testing and rspec
- New fingerprints
- Removal of trailing whitespace
- Small changes to make some fingerprints more consistent
=> Various fingerprint updates

xml/snmp_sysdescr.xml
Adding an additional fingerprint for kyocera printers with the banner name KYOCERA Document Solutions Printing System
=> Add fingerprint to kyocera printers

xml/mysql_banners.xml
Additional MariaDB banners that current recog is not matching against
Running the unit tests with 
bin/recog_verify xml/mysql_banners.xml
=> Additional MariaDB banners 

xml/http_cookies.xml, xml/http_servers.xml
This PR contains HTTP related fingerprints pulled from a recent Project Sonar survey of the Internet.
*Note*: It includes updates for multiple SAP products in particular.
Improvements in coverage
`rspec` and built in tests.
=> Project Sonar HTTP updates

xml/http_servers.xml
This PR contains more tweaks to SAP products
Coverage
`rspec`, local testing
=> SAP Tweaks

cpe-remap.yaml, xml/http_servers.xml
This PR adds or tweaks vendor and/or product value with the goal of improving CPE coverage. It also adds a few new fingerprints. The work here is based on Project Sonar data.
`rspec`, `recog_verify`, and local testing.
=> Project Sonar: CPE - Improved coverage in http_servers.xml

xml/html_title.xml, xml/http_servers.xml
RealVNC and TigerVNC fingerprint additions/improvements
Coverage
`rspec`, local tests
=> Project Sonar: RealVNC updates

xml/http_servers.xml
Fingerprint additions / tweaks for SonicWall and Cisco Expressway products
=> Project Sonar: SonicWall/Cisco Expressway

xml/snmp_sysdescr.xml
This PR addresses a few issues in PR #286. It also adds some tests to a few of the fingerprints that were missing them.
CC @nstylepro 
`rspec`
`bin/recog_verify xml/snmp_sysdescr.xml`
=> Siemens updates in snmp_sysdescr.xml (tweak PR#286)

cpe-remap.yaml, xml/favicons.xml, xml/ftp_banners.xml, xml/html_title.xml, xml/http_cookies.xml, xml/http_servers.xml, xml/ldap_searchresult.xml, xml/operating_system.xml, xml/smb_native_os.xml, xml/smtp_banners.xml, xml/smtp_vrfy.xml, xml/snmp_sysdescr.xml, xml/x509_issuers.xml, xml/x509_subjects.xml
The intent of this PR is to improve CPE generation when using `update_cpes.py` by:
- Updating remap entries
- Tweaking existing fingerprints to be more correct (Based on NIST + subjective perspective)
**NOTE**: All CPE changes in this PR were generated using `update_cpes.py` and the most recent version of the NIST database.
Improved output
Execution of `update_cpes.py` and verifying that the changes are in line with expectations
rspec
=> CPE: Update remapping / tweak fingerprints

identifiers/hw_product.txt, identifiers/os_product.txt, identifiers/service_family.txt, identifiers/service_product.txt, identifiers/vendor.txt, xml/http_servers.xml, xml/ssh_banners.xml
Have several fingerprints iam adding one for Zyxel SSH. and three http_server for server header data returned from ssdp M-SEARCH request on UDP port 1900, included for Pelco camera, Netgear AP router and a generic response 
Attempt to add some new IoT/embedded device fingerprints
Tested again lab device and validate with current recog scripts
New fingerprints
=> Adding a few fingerprints to http and ssh

identifiers/hw_family.txt, identifiers/hw_product.txt, identifiers/os_device.txt, identifiers/os_product.txt, identifiers/service_product.txt, identifiers/vendor.txt, update_cpes.py, xml/sip_banners.xml, xml/sip_user_agents.xml
This PR updates SIP related fingerprint databases based on data collected by Project Sonar
Every new fingerprint has examples, `rspec`, and Github tests.
Fingerprint additions.
=> SIP related updates

cpe-remap.yaml, identifiers/hw_device.txt, identifiers/hw_family.txt, identifiers/hw_product.txt, identifiers/os_family.txt, identifiers/os_product.txt, identifiers/service_family.txt, identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_servers.xml, xml/ntp_banners.xml, xml/rtsp_servers.xml, xml/snmp_sysdescr.xml, xml/ssh_banners.xml, xml/telnet_banners.xml
This PR is cleanup and normalization after the last couple of PRs.
local tests, `rspec`, etc.
=> Housekeeping / Fixup after recent merges

identifiers/hw_product.txt, identifiers/service_product.txt, identifiers/vendor.txt, xml/sip_banners.xml, xml/smtp_banners.xml
This PR contains additional SMTP fingerprints and tweaks.
rspec and examples in the fingerprints
=> SMTP updates

cpe-remap.yaml, identifiers/hw_family.txt, identifiers/hw_product.txt, identifiers/os_product.txt, identifiers/service_family.txt, identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_servers.xml, xml/http_wwwauth.xml, xml/snmp_sysdescr.xml, xml/x509_issuers.xml, xml/x509_subjects.xml
The PR contains:
- Various updates to x.509 subject fingerprints
- Updates to other fingerprints for consistency sake.
rspec, built in example tests
- Content
=> x.509 related updates

cpe-remap.yaml, xml/dns_versionbind.xml, xml/html_title.xml, xml/http_servers.xml, xml/telnet_banners.xml
This PR includes:
- a couple minor HTTP related additions
- tweaks of a couple regex in order to remove warnings about duplicate character classes.
=> HTTP fingerprints, regex tweaks

xml/mysql_banners.xml
Change to one of the regex patterns that looks to have missed having a -log appended to the end of the regex pattern
If a mariadb focal banner contained -log we were failing to match
Adding a option -log to the regex pattern
=> Adding -log to regex

.github/workflows/verify.yml
Adds a GitHub workflow to run `bin/recog_standardize` on any modified XML fingerprint files similar to #371. This will help contributors and pull request reviewers verify that each fingerprint asserts known identifiers.
Help contributors and pull request reviewers catch concerns.
```
diff --git a/xml/http_servers.xml b/xml/http_servers.xml
index 1fe068b..212f3f7 100644
--- a/xml/http_servers.xml
+++ b/xml/http_servers.xml
@@ -4552,7 +4552,8 @@
<param pos="0" name="os.product" value="FortiOS"/>
<param pos="0" name="os.device" value="Firewall"/>
<param pos="0" name="os.cpe23" value="cpe:/o:fortinet:fortios:-"/>
-    <param pos="0" name="hw.vendor" value="Fortinet"/>
+    <param pos="0" name="hw.vendor" value="DNE1"/>
+    <param pos="0" name="hw.dne" value="DNE2"/>
</fingerprint> …
```
=> Add GitHub verify workflow

identifiers/service_product.txt, xml/favicons.xml, xml/html_title.xml, xml/tls_jarm.xml
Adds three fingerprints for [Covenant](https://github.com/cobbr/Covenant) .NET C2 framework.
More C2 fingerprints for recog.
* Covenant installed and run following the directions for using [Docker](https://github.com/cobbr/Covenant/wiki/Installation-And-Startup#option-2---docker)
* `rake tests`
=> Add Covenant C2 fingerprints

xml/http_cookies.xml
Addresses all warnings by incorporating real data as examples into http_cookies.xml
Eliminate warnings
=> Fix all examples in http_cookies.xml by adding/improving examples

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
* Adds 3 [Adminer](https://www.adminer.org/) fingerprints.
* Corrects a vertical bar literal within a fingerprint introduced in #401
Fingerprint more services.
* `rake tests`
=> Add Adminer fingerprints

identifiers/service_product.txt, xml/favicons.xml, xml/html_title.xml
Adds 2 [Apache Solr](https://solr.apache.org/) fingerprints.
Fingerprint more services.
* `rake tests`
=> Add Apache Solr fingerprints

identifiers/os_product.txt, identifiers/vendor.txt, xml/http_servers.xml
Adds a fingerprint for the [SerenityOS](https://github.com/SerenityOS/serenity) built-in [web server component](https://github.com/SerenityOS/serenity/tree/master/Userland/Services/WebServer).
* `rakes tests`
* `./bin/recog_verify xml/http_servers.xml`
=> Add SerenityOS web server fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/http_servers.xml
Adds 2 [mitmproxy](https://github.com/mitmproxy/mitmproxy) fingerprints.
* `rake tests`
=> Add mitmproxy fingerprints

identifiers/os_family.txt, xml/html_title.xml
Adds an HTML title fingerprint for the DrayTek Vigor network equipment.
* `rake tests`
=> Add DrayTek Vigor network equipment fingerprint

cpe-remap.yaml, identifiers/vendor.txt, xml/html_title.xml, xml/http_servers.xml
Adds HTML title fingerprint for Xiongmai Technology DVR and IP Camera NetSurveillance web interface. Updates existing HTTP server fingerprint for uc-httpd to emit cpe23.
* `rake tests`
=> Xiongmai Technology DVR and IP Camera NetSurveillance web interface

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
Adds 3 fingerprints for [mongo-express](https://github.com/mongo-express/mongo-express), a web-based MongoDB admin interface.
* `rake tests`
=> Add mongo-express fingerprints

README.md
Updates the default branch rename instructions.
Adds missing and optional steps for updating a user's fork after the default branch rename.
Worked through the steps after the repo split changes were merged.
=> Update default branch rename instructions

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/tls_jarm.xml
Adds two fingerprints for [openHAB](https://www.openhab.org/) open-source home automation software.
* `rake tests`
=> Add openHAB fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml
Adds favicon fingerprint for [Home Assistant](https://www.home-assistant.io/) open-source home automation software.
* `rake tests`
=> Add Home Assistant favicon fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/http_servers.xml
Adds an HTTP server fingerprint for the [Ballerina](https://github.com/ballerina-platform/ballerina-lang) programming language's [HTTP module](https://lib.ballerina.io/ballerina/http/latest).
* `rake tests`
=> Add Ballerina programming language HTTP module fingerprint

identifiers/service_product.txt, xml/http_servers.xml
Adds HTTP server fingerprint for Microsoft Azure Application Gateway.
See [What is Azure Application Gateway?](https://docs.microsoft.com/en-us/azure/application-gateway/overview) for more information on the service. Based on the [Feature comparison between v1 SKU and v2 SKU](https://docs.microsoft.com/en-us/azure/application-gateway/overview-v2#feature-comparison-between-v1-sku-and-v2-sku) it appears there have been at least two versions of the service, although, I don't have samples from the v1 server header.
* `rake tests`
=> Add Microsoft Azure Application Gateway fingerprint

identifiers/service_family.txt, identifiers/service_product.txt, identifiers/vendor.txt, xml/http_servers.xml
Adds HTTP server fingerprint for Alibaba Cloud, a.k.a. Aliyun, Object Storage Service (OSS).
1. https://cn.aliyun.com/product/oss
> 阿里云对象存储OSS（Object Storage Service）是一款海量、安全、低成本、高可靠的云存储服务，提供99.9999999999%(12个9)的数据持久性，99.995%的数据可用性。
Google Translate:
> Alibaba Cloud Object Storage OSS (Object Storage Service) is a massive, secure, low-cost, and highly reliable cloud storage service that provides 99.9999999999% (12 9s) of data durability and 99.995% of data availability.
2. [Alibaba Cloud Object Storage Service (OSS)](https://www.alibabacloud.com/product/object-storage-service)
3. [Aliyun OSS Emulator](https://github.com/aliyun/oss-emulator)
> oss-emulator 轻量级的OSS服务模拟器，提供与OSS服务相同的API接口。
Google Translate:
> oss-emulator is a lightweight OSS service emulator that provides the same API …
=> Add Alibaba Cloud Object Storage Service (OSS) fingerprint

xml/favicons.xml
Add a favicon for synology
Tested on my local NAS
- New feature (non-breaking change which adds functionality.
=> Add a favicon for synology DSM

xml/x509_issuers.xml
Add a x509_issuers fingerprint for proxmox
Tested on my local instance via Rumble.run
=> Add a x509_issuers fingerprint for proxmox

xml/dhcp_vendor_class.xml, xml/snmp_sysdescr.xml, xml/snmp_sysobjid.xml
Add new fingerprints to snmp_sysdescr.xml and snmp_sysobjid.xml for [Aruba Switch devices](https://www.arubanetworks.com/en-gb/products/switches/)
- `rake tests`
- `./bin/recog_verify  xml/snmp_sysdescr.xml`
- `./bin/recog_verify  xml/snmp_sysobjid.xml`
=> Add Aruba fingerprints via SNMP

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml, xml/imap_banners.xml, xml/pop_banners.xml, xml/x509_subjects.xml
Updates the existing Zimbra fingerprints (http_cookies.xml, imap_banners.xml, pop_banners.xml) and adds new Zimbra Collaboration fingerprints (favicons.xml, html_title.xml, x509_subjects.xml).
Improved coverage and updated vendor/product information.
* `bundle exec ./bin/recog_verify {filename}`
* `rake tests`
=> Update and add new Zimbra Collaboration fingerprints

identifiers/service_product.txt, xml/x509_issuers.xml
Adds [Kubernetes minikube](https://github.com/kubernetes/minikube) x509 issuer fingerprint.
* `bundle exec ./bin/recog_verify xml/x509_issuers.xml`
* `rake tests`
=> Add Kubernetes minikube x509 issuer fingerprint

identifiers/service_product.txt, xml/http_servers.xml
Adds Python BaseHTTP server fingerprint.
* `rake tests`
=> Add Python BaseHTTP fingerprint

xml/dhcp_vendor_class.xml, xml/http_servers.xml
Adds fingerprint for Gunicorn with no version.
* `rake tests`
=> Add Gunicorn with no version fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml
Adds OpenKM Document Management System favicon fingerprint.
* `rake tests`
=> Add OpenKM Document Management System fingerprint

identifiers/service_product.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
Adds Atlassian Bitbucket fingerprints.
* `bundle exec ./bin/recog_verify FILE`
* `rake tests`
=> Add Atlassian Bitbucket fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml
Adds [Mayan EDMS](https://www.mayan-edms.com/) document management system fingerprint
* `rake tests`
=> Add Mayan EDMS document management system fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml
Adds [SalesAgility SuiteCRM](https://suitecrm.com/) fingerprints.
* `bundle exec ./bin/recog_verify FILE`
* `rake tests`
=> Add SalesAgility SuiteCRM fingerprints

cpe-remap.yaml, identifiers/service_product.txt, xml/favicons.xml, xml/html_title.xml, xml/http_servers.xml
Adds [ManageEngine PAM360](https://www.manageengine.com/privileged-access-management/) fingerprints.
* `/themes/passtrix/V5600/images/ps_ico.ico`:
```
$ file ps_ico.ico
ps_ico.ico: MS Windows icon resource - 1 icon, -22x256, 32 bits/pixel
$ md5 ps_ico.ico
MD5 (ps_ico.ico) = 895eea03838bb521717d632eec739e57
```
* `/favicon.ico`:
```
favicon.ico: MS Windows icon resource - 1 icon, -22x256, 32 bits/pixel
MD5 (favicon.ico) = 895eea03838bb521717d632eec739e57
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/html_title.xml xml/http_servers.xml`
* `rake tests`
=> Add ManageEngine PAM360 fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/http_servers.xml
Adds HTTP fingerprint for [CrowCpp/Crow](https://github.com/CrowCpp/Crow), a C++ framework for web services.
* `rake tests`
=> Add Crow C++ framework for web services fingerprint

identifiers/os_product.txt, identifiers/vendor.txt, xml/dhcp_vendor_class.xml
New fingerprints based on captured vi_vendor_class strings
Dell Printers
Mitel IP Phone
BrightSign Media Server
Digium D Series IP Phone
Dell iDRAC
Linux with Busybox service
Busybox versions: https://busybox.net/downloads/binaries/
Digium Firmware: http://downloads.digium.com/pub/telephony/res_digium_phone/firmware/
=> New dhcp vendor class fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml
Adds [Papermerge](https://www.papermerge.com/) document management system fingerprints.
* `<link rel="shortcut icon" type="image/png" href="/static/admin/img/favicon.ico"/>`:
```
favicon.ico: MS Windows icon resource - 1 icon, 31x30, 32 bits/pixel
MD5 (favicon.ico) = 1abc8c6149e4602d59eace535229217e
```
* `rake tests`
=> Add Papermerge document management system fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/ftp_banners.xml, xml/http_servers.xml
Adds 2 [Medusa](http://www.nightmare.com/medusa/), extensible Internet server framework, fingerprints.
* `bundle exec ./bin/recog_verify xml/ftp_banners.xml xml/http_servers.xml`
* `rake tests`
=> Add Medusa extensible Internet server framework fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml
Adds 2 [Supervisord Supervisor](http://supervisord.org/) web interface fingerprints.
* `<link href="images/icon.png" rel="icon" type="image/png" />`
```
$ file icon.png
icon.png: PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
$ md5 icon.png
MD5 (icon.png) = dca8de269506757ce7f61c276991e1c5
```
* `rake tests`
=> Add Supervisord Supervisor web interface fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
Adds 3 [qdPM](https://qdpm.net/), project management tool, fingerprints.
* `<link rel="shortcut icon" href="/favicon.ico" />`
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 24 bits/pixel
MD5 (favicon.ico) = b0bd48e57fd398c5da8ae8f2ccc8d90d
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/html_title.xml xml/http_cookies.xml`
* `rake tests`
=> Add qdPM fingerprints

xml/dhcp_vendor_class.xml
Fingerprint for devices running ChromeOS based on observed DHCP traffic.
Ran `recog_verify`, `recog_standardize` and `update_cpes`
=> DHCP fingerprint for ChromeOS devices

cpe-remap.yaml, xml/dhcp_vendor_class.xml
Fingerprint for Compaq Remote Insight based on observed DHCP traffic
Ran `recog_verify`, `recog_standardize` and `update_cpes`
=> DHCP fingerprint for Compaq Remote Insight

xml/html_title.xml
Adds [OpenKM Document Management System](https://www.openkm.us/en/open-source-document-management-system.html) HTML title fingerprint.
Fingerprinted OpenKM version 6.3.12.
Improved coverage and followup to #480.
* `rake tests`
=> Add OpenKM Document Management System HTML title fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
Adds 3 MGT-COMMERCE GmbH [CloudPanel](https://www.cloudpanel.io/) fingerprints. Thanks to @todb-r7 for providing access to a test instance!
Fingerprinted CloudPanel v2.1.0.
* `<link rel="icon" type="image/svg+xml" href="/assets/images/favicon.svg?v=2.1.0">`
```
$ file favicon.svg
favicon.svg: SVG Scalable Vector Graphics image
$ md5 favicon.svg
MD5 (favicon.svg) = dbe63c6d86ca97a4b20420e932c5b0bb
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/http_cookies.xml xml/html_title.xml`
* `rake tests`
=> Add MGT-COMMERCE GmbH CloudPanel fingerprints

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
Adds 3 [FileRun](https://filerun.com/) fingerprints.
Fingerprinted FileRun 20220519.
* `<link rel="icon" type="image/png" href="http://localhost/images/favicons/192.png?v=20220519" sizes="any">`
```
$ file 192.png
192.png: PNG image data, 192 x 192, 8-bit/color RGBA, non-interlaced
$ md5 192.png
MD5 (192.png) = 188caa0ab159a5ceaca86922c293f62f
```
* `<link rel="icon" type="image/svg+xml" href="http://localhost/images/favicons/256.svg?v=20220519">`
```
$ file 256.svg
256.svg: SVG Scalable Vector Graphics image
$ md5 256.svg
MD5 (256.svg) = fdfbcf58b378b0fba43ba86e41a824fe
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/html_title.xml xml/http_cookies.xml`
* `rake tests`
=> Add FileRun fingerprints

identifiers/hw_product.txt, xml/dhcp_vendor_class.xml
DHCP fingerprint for Dell Wyse-100 thin client
Ran `rake tests`, `recog_verify`, `recog_standardize`, `update_cpes.py`
=> DHCP fingerprint for Dell Wyse-1000 thin client

xml/favicons.xml, xml/html_title.xml, xml/http_cookies.xml
Updates the existing [ManageEngine ADAudit Plus](https://www.manageengine.com/products/active-directory-audit/) fingerprints and add fingerprints for HTTP cookies.
Fingerprinted ADAudit Plus version 7.1.0 build 7101.
* `<link rel="icon" type="image/png" href="assets/images/favicon-16x16.png" sizes="16x16">`
```
$ file favicon-16x16.png
favicon-16x16.png: PNG image data, 16 x 16, 8-bit/color RGBA, non-interlaced
$ md5 favicon-16x16.png
MD5 (favicon-16x16.png) = ee20526df4d69f7b02ee107458d8d679
```
* `<link rel="icon" type="image/png" href="assets/images/favicon-32x32.png" sizes="32x32">`
```
$ file favicon-32x32.png
favicon-32x32.png: PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
$ md5 favicon-32x32.png
MD5 (favicon-32x32.png) = 661b80a4dde45fee1079113ce0323336
```
* `<link …
=> Update existing ManageEngine ADAudit Plus and add HTTP Cookies fingerprints

cpe-remap.yaml, identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml
Adds 2 [Fortra GoAnywhere MFT](https://www.goanywhere.com/products/goanywhere-mft) fingerprints. Note, the CPE remapping should be revisited when NVD updates the CPE entry for the vendor name change and possibly the product name as well since that is "GoAnywhere MFT" and not "GoAnywhere Managed File Transfer".
Fingerprinted GoAnywhere MFT version 7.0.3.
```
favicon.ico: MS Windows icon resource - 3 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = fa73151a3a3b610eaca4a7a5a78cc775
```
* `favicon.ico` (alternative from versions 6.x and 5.x)
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 8 bits/pixel
MD5 (favicon.ico) = 16d472e9624492b9398e7645c46d1f25
```
Improved …
=> Add Fortra GoAnywhere MFT fingerprints

xml/dhcp_vendor_class.xml
Added Cisco Telepresence Peripheral to dhcp_vendor_class
rake tests
New feature (non-breaking change which adds functionality)
=> Added Cisco Telepresence Peripheral to dhcp_vendor_class

identifiers/os_product.txt, xml/dhcp_vendor_class.xml
Added Juniper SSL VPN to dhcp_vendor_class
Added ive_os to os_product.txt
https://support.juniper.net/support/eol/software/ive/
Extended coverage
rake tests
=> Added Juniper SSL VPN to dhcp_vendor_class

identifiers/service_product.txt, identifiers/vendor.txt, xml/http_cookies.xml
Adds a new `Set-Cookie` fingerprint for Laravel - a PHP web application framework
Run the server form vulhub:
```
$ docker run -p 9001:80 vulhub/laravel:8.4.2
```
Curl output example:
```
$ curl -I http://localhost:9001
HTTP/1.1 200 OK
Date: Mon, 13 Mar 2023 16:59:08 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.4.15
Cache-Control: no-cache, private
Set-Cookie: XSRF-TOKEN=eyJpdiI6Im1KOUxDMC9BeTJCZkllSklkYXF3eGc9PSIsInZhbHVlIjoibDFoQ1JZcVdobjdyaHQ2SjNoR1dQaS94Qnk5THIxYzNKclZGekVEVzd0VHE0T3NBNkN1Y0FqaGxsVVg0SzhGV3NKM1dNSzlkc2NabDBHT2twcUVFMTNmL3JMMGxLSDh1cUlaQzhqMEZpckpDbkx0REg2UkNtR21rRkw5N05WR1ciLCJtYWMiOiJkZTZhMTc2ZTMzZmMwODYyOGE1OWRkN2U0Y2JjOTI5MDZiY2UzNGZhNjQ4OGU5ZDY3NDkzZjQ3NjYwYmViOTVkIn0%3D; expires=Mon, 13-Mar-2023 18:59:08 GMT; Max-Age=7200; path=/; samesite=lax …
```
=> Add Set-Cookie fingerprint for Laravel

README.md
Adds multiple examples of running recog's fingerprinting capabilities
Should help reduce the barrier to seeing examples of Recog's fingerprint capabilities
The documentation steps have been followed
Documentation
=> Add examples of testing matches

identifiers/service_product.txt, identifiers/vendor.txt, xml/html_title.xml
Adds [Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx) document management system HTML title fingerprint.
Fingerprinted Paperless-ngx version 1.13.0.
```
favicon.ico: MS Windows icon resource - 6 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = 32a136901323f2b2eb12d529e10bf064
```
The favicon hash matches both Paperless-ng and Paperless.
* `rake tests`
=> Add Paperless-ngx document management system HTML title fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/html_title.xml
Adds [Paperless-ng](https://github.com/jonaswinkler/paperless-ng) document management system HTML title fingerprint.
Fingerprinted Paperless-ng version 1.5.0.
```
favicon.ico: MS Windows icon resource - 6 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = 32a136901323f2b2eb12d529e10bf064
```
The favicon hash matches both Paperless-ngx and Paperless.
* `rake tests`
=> Add Paperless-ng document management system HTML title fingerprint

xml/favicons.xml
Adds [3CX](https://www.3cx.com/) Phone System Management Console favicon fingerprint.
Fingerprinted unknown product version.
```
favicon.ico: PNG image data, 32 x 32, 16-bit/color RGBA, non-interlaced
MD5 (favicon.ico) = 619e4452da00dad6c3d7b5fd99b9390e
```
* `rake tests`
=> Add 3CX Phone System Management Console favicon fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml
Adds 2 fingerprints for [MeterSphere](https://metersphere.io/), an open-source continuous testing platform.
Fingerprinted unknown product version.
```
favicon.ico: PNG image data, 26 x 30, 8-bit colormap, non-interlaced
MD5 (favicon.ico) = d6abc57c65b787c0418803ffc75a7fa0
```
* `rake tests`
=> Add MeterSphere fingerprints

xml/html_title.xml
Improve freebox fingerprinting
- There isn't always trailing text
- It's Linux-based
On my LAN
=> Improve freebox fingerprinting

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml
Added Logipacs favicon fingerprint.
Improved coverage.
- bundle exec ./bin/recog_verify xml/favicons.xml
=> Add Logipacs Favicon Fingerprint

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml
Add new favicon fingerprints for medical imaging systems and radiology platforms.
Improved Coverage for medical platforms.
- bundle exec ./bin/recog_verify xml/favicons.xml
=> Add new fingerprints for medical imaging systems and radiology platforms

xml/favicons.xml
Add a missing Radarr favicon
On my lan
=> Add a missing Radarr favicon

identifiers/fields.txt, xml/x509_issuers.xml
Improve Chromecast x509 issuer fingerprinting
On my lan
=> Improve Chromecast x509 issuer fingerprinting

xml/http_servers.xml
Add a fingerprint for the freebox' FbxWSD server
On my lan
=> Add a fingerprint for the freebox' FbxWSD server

xml/rtsp_servers.xml
- Add version grabbing
- Add an example
On my lan
=> Improve freebox's rtsp fingerprinting

identifiers/service_product.txt, identifiers/vendor.txt, xml/html_title.xml
Add an html_title fingerprint for miniflux
Add an html_title fingerprint for miniflux
On a friend's instance
=> Add an html_title fingerprint for miniflux

identifiers/service_product.txt, identifiers/vendor.txt, xml/favicons.xml, xml/html_title.xml, xml/http_servers.xml, xml/x509_subjects.xml
Add fingerprints for OPNSense
OPNSense if like fpSense, but more popular and better™.
On a friend's lan.
=> Add fingerprints for OPNSense

README.md
Testing matches section can be included in list.
Catching up Table of Contents as followed by the rest of section.
N/A.
- Documentation
=> docs(README): section Testing matches list

identifiers/os_product.txt, xml/sip_banners.xml
I am updating the SIP record for Cisco to be backward compatible.
=> Update SIP banner to be backward compatible

.github/workflows/ci.yml, identifiers/os_family.txt, identifiers/os_product.txt, xml/snmp_sysdescr.xml
- Added SNMP fingerprinting for Cisco FTD
- Changed pipeline ubuntu version to a fixed one to remove pipeline build errors.
Ran `bin/recog_verify xml/snmp_sysdescr.xml`
=> SNMP-fingerprinting-for-Cisco-FTD

identifiers/os_family.txt, xml/snmp_sysdescr.xml
Added SNMP detection for Cisco RV routers
=> Added SNMP detection for Cisco RV routers

xml/smtp_banners.xml
=> Revert "Update smtp_banners.xml"
