rapid7/recog

lib/recog/fingerprint.rb
lib/recog/version.rb

This fixes #Fingerprint.name entries to remove the newlines. This results in a much more readable string:
Before:
```
Embedded HTTP server used by many vendors and device\n      types, including APC, 3Com, Andover Controls, Cisco VoIP, D-Link,\n      Extreme Networks, Foundry Networks, Konica Minolta, Kronos\n      Timekeeper, McDATA, Netopia, Nortel Networks, Power Measurement Ltd,\n      and Xerox.
```
After:
```
Embedded HTTP server used by many vendors and device types, including APC, 3Com, Andover Controls, Cisco VoIP, D-Link, Extreme Networks, Foundry Networks, Konica Minolta, Kronos Timekeeper, McDATA, Netopia, Nortel Networks, Power Measurement Ltd, and Xerox.
```
Only downstream impact today is Recog matching through DAP

Remove newlines from descriptions.

---

xml/snmp_sysdescr.xml

I discovered this while reviewing #13.  I don't know how long this has been wrong, but the description, vendor and device were all wrong.  They have been corrected.
```rspec``` passes.

Correct Tektronix printer SNMP fingerprint

---

xml/http_servers.xml

Fingerprints for two additional Python based HTTP servers: 1. Tornado Python web framework and 2. SimpleHTTP

Add fingerprints for Python HTTP servers

---

lib/recog/matcher.rb

This code is only used by recog_match, but there were some problems:
* It was matching the line against the raw regex of the fingerprint rather than matching the fingerprint against the line 
* It was repeating the extraction logic already done in fingerprint.rb
This is not spec'd in the first place and may be deprecated in the future anyway, but the existing pass/fail functionality is maintained, however as you can see the output is a little different (caused by now using the correct match method):
Old:
```
$  echo "mbfcookie=adafadf" | ./bin/recog_match.rb xml/http_cookies.xml -
MATCH: {"cookie"=>"mbfcookie", "service.family"=>"Joom!Fish", "service.product"=>"Joom!Fish", "data"=>"mbfcookie=adafadf"}
$  echo "mabfcookie=adafadf" | ./bin/recog_match.rb xml/http_cookies.xml -
FAIL: …
```

Remove duplicate match/extract logic from recog_match

---

Gemfile
lib/recog/fingerprint.rb
spec/lib/fingerprint_self_test_spec.rb

This simply takes the capture validation (too many captures, too few) logic from the functional recog code and moves it to the specs instead.  In doing this, it will flag 8 fingerprints as having incorrect groups (which I'll also fix in this PR but want to show that rspec will flag them)

Move all capture validation to rspec

---

spec/lib/fingerprint_self_test_spec.rb
xml/h323_callresp.xml
xml/http_cookies.xml
xml/pop_banners.xml
xml/smb_native_os.xml
xml/smtp_banners.xml
xml/snmp_sysdescr.xml
xml/ssh_banners.xml
xml/upnp_banners.xml

The logic for detecting cases where the capture groups in the regular expression don't align with what is actually used (extracted) was getting a little out of hand so i simplified it a bit, which in turn caught several more defects with the existing fingerprints.  I've done my best to fix all of the fingerprints, add examples where possible, etc.  
On a related note, we should strive to ensure that any future PRs that modify any existing fingerprints ensure that an example exists and the expectations for what is extracted are checked.  A number of the fingerprints which I've fixed in this PR could have been caught with a simple test, but for a variety of reasons lots of what started recog is missing examples and extraction tests.

Tighten capture/extraction spec even further, correct more miscaptures/etc

---

.travis.yml
Gemfile
Rakefile
features/support/env.rb
spec/lib/fingerprint_self_test_spec.rb

When I originally tried this, I guess I didn't validate that it actually ran cucumber in Travis.  It should now.

Run all tests in Travis

---

README.md
lib/recog/fingerprint/regexp_factory.rb
spec/lib/recog/fingerprint/regexp_factory.rb

In updating README.md for #20, I noticed that `flags` was not documented.  When I went to document it, I realized it wasn't clear how this is used and when I figured that out I realized that it would be nice to be able to use a subset of the actual Regexp constants rather than our current model which is part GNU RE and part Nexpose leftovers.  Eventually this probably needs to be removed entirely or re-implemented differently.

Document, enhance and test flags

---

xml/http_servers.xml

According to what I've been able to determine, this Server header is exclusive to HP ProCurve devices despite being very simplistic.

Add HTTP Server fingerprints for HP ProCurve devices

---

xml/http_wwwauth.xml

This adds fingerprints for some (all?) HP ProCurve switches and hubs using the realm presented during authentication.

Add HTTP auth fingerprints for HP ProCurve switches and hubs

---

xml/http_cookies.xml

Adds an explicit fingerprint for HP System Management Homepage (SMH) as well as adds ignored fingerprints for common generic cookies that can't be used to pinpoint anything.

Set-Cookie fingerprint improvements

---

README.md

The Best Practices section notes the importance of simplifiying fingerprints and flexible version number matching. Change made per suggestion of @jhart-r7 in #20.

Added Best Practices section

---

xml/ntp_banners.xml

This makes the existing F5 NTP regex more closely match the one known example, but also adds a fingerprint for OpenVMS AXP which was previously matching on the existing F5 fingerprint due to it being too loose.

Fix #37 -- Add OpenVMS AXP NTP fingerprint and correct F5 BIG-IP

---

Rakefile

I believe this fixes https://github.com/rapid7/recog/issues/31 by simply updating `release` tag to point to the most recent release as part of `rake release`.    Note that this `release` task does not overwrite the existing `release` task caused by the inclusion right before, but rather appends to it per http://ruby-doc.org/core-1.9.3/doc/rake/rakefile_rdoc.html#label-Multiple+Definitions.  Furthermore, I don't believe any of the API stuff mentioned in #31 is necessary, because github appears to automatically release new releases that correspond to the current tags.
I have tested this a bit in my own fork, but it had the unfortunate side effect of me releasing several bogus versions of the gem (which I've since yanked).  That may be the only way to test this but I'll think about it more. …

Tag latest release as 'release', fixes #31

---

Rakefile

Per discussions elsewhere, the work done in #40 which fixed https://github.com/rapid7/recog/issues/31 and got recog to a point that would streamline the release of Recog releases into other products isn't necessary as it was just a stop-gap measure until GES could implement the more ideal solution.
This PR simply undoes that work.  No need to issue a release when landing this.
After this lands, I'll clean up any tags or release issues to return everything to normal.

Revert Rakefile to e038f1e, undo work in #40 for #31

---

xml/http_servers.xml

As suggested in #20 I modified the 19 patterns that used `((?:\d+\.)+\d+)` to match the service version to also allow for major only style version numbers.
```
FAIL: SentinelProtectionServer/7
FAIL: SentinelKeysServer/1
FAIL: CherryPy/3
FAIL: HP Web Jetadmin/2 (Win32) mod_auth_sspi/1.0.1 mod_ssl/2.0.50 OpenSSL/0.9.6m
FAIL: Lotus Expeditor Web Container/6
FAIL: Mbedthis-Appweb/2
FAIL: Avaya CMBE/2
FAIL: Rapid Logic/1
FAIL: mini_httpd/1 23jun2000
FAIL: thin 2 codename Flaming Astroboy
FAIL: Avocent DSView 3/3
FAIL: Mongrel 1
FAIL: Microplex emHTTPD/1
FAIL: UPS_Server/1
FAIL: JC-HTTPD/1
FAIL: JC-SHTTPD/1
FAIL: Oracle XML DB/Oracle9i Enterprise Edition Release 9 - Production
FAIL: Ews/1
FAIL: GFE/1
```
```
MATCH: {"matched"=>"Embedded web server in SafeNet's memory key dongles.", …
```

Modified 19 patterns to allow major only style version number

---

xml/ssh_banners.xml

I wasn't sure what would be the best way to classify the OpenVMS SSH service versions.  According to the documentation the SSH server is based on SSH2 software from SSH Communication Security.
Is using this as the service.component.version appropriate? Would it be better to use either the SSH Secure Shell version or the TCP/IP Services for openVMS version as the service.version parameter instead?

Comware and OpenVMS ssh

---

xml/mysql_banners.xml
xml/mysql_error.xml

Add initial MySQL banner support

Add initial MySQL banner support

---

xml/snmp_sysdescr.xml

This fixes #44.  `rspec` passes before and after this change.

Correct FreeBSD SNMP fingerprint

---

xml/mysql_banners.xml

Change to a regex that was causing this warning 
`recog-1.0.27/lib/recog/fingerprint/regexp_factory.rb:33: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression`
#47

Change redundant ? to * fixes rapid7/recog#47

---

xml/mdns_device-info_txt.xml
xml/mdns_workstation_txt.xml

This PR contains 2 new XML fingerprint files which each correspond to TXT records that can be retrieved from mDNS endpoints.
The TXT record for _device-info._tcp.local. (which sometimes needs the host name prepended for the query) may contain information that can be used to fingerprint certain systems, in particular Mac OS X.
The TXT record for _workstation._tcp.local. (ditto w/r/t prepending the hostname) may contain information that can be used to fingerprint the mDNS software, in particular Avahi.
Note that due to the nature of mDNS the service may need to be queried from the same subnet as the host.

Initial fingerprints for mDNS: Avahi, Mac OS X, AirPort

---

.travis.yml
lib/recog/version.rb
recog.gemspec

Remove 1.9.3 from Travis
Set minimum ruby version for the gem to 2.1+
Bump recog version
I can still build the gem on 1.9.3 but it won't install:
```
$  gem build recog.gemspec && gem install recog-1.0.18.gem 
Successfully built RubyGem
Name: recog
Version: 1.0.18
File: recog-1.0.18.gem
ERROR:  Error installing recog-1.0.18.gem:
recog requires Ruby version >= 2.1.
```

EOL 1.9.3 support, fixes #26

---

xml/snmp_sysdescr.xml

The new example banner contains some hardware information: X460 series 24-port switch.
I have no idea what else this might look like for other hardware, so it's very likely this will still miss some banners. This was just one banner found to be missing a match recently. I may have more examples coming up to improve this further.
Test:
```shell
$ bin/recog_match xml/snmp_sysdescr.xml xos15.txt
MATCH: {"matched"=>"Extreme Networks Switches", 
"os.vendor"=>"Extreme Networks", 
"os.device"=>"Switch", 
"os.product"=>"XOS", 
"os.version"=>"15.6.1.4", 
"data"=>"ExtremeXOS (X460-24x) version 15.6.1.4 v1561b4 by release-manager on Tue Sep 30 14:06:19 EDT 2014"}
```
cc @jhart-r7

Update SNMP regex for Extreme Networks XOS v15

---

xml/snmp_sysdescr.xml

The H3C SNMP fingerprints use a vendor/product of H3C/Comware, which is in-line with https://github.com/rapid7/recog/blob/master/xml/ssh_banners.xml#L781-791.  Note that unlike the fingerprints above, in https://github.com/rapid7/recog/blob/master/xml/snmp_sysdescr.xml#L2707-2766, these do _not_ use HP in the vendor name -- the thinking here is that yes, HP did eventually acquire H3C, but purely based on these banners we cannot say that these are HP.

Add SNMP sysDesc fingerprints for H3C Comware and VMware vSphere Management Assistant

---

xml/ntp_banners.xml

Some HP-UX systems don't list a processor.  This is fine.

Add NTP fingerprint for HP-UX when there is no processor

---

xml/ftp_banners.xml

The regex was a little too restrictive and wasn't catching one variant of the FTP banner.

Improve regex for Axis network cameras

---

xml/smtp_banners.xml

Improve some SMTP fingerprints

---

xml/ntp_banners.xml

These will typically only listen/respond locally, but just in case...
/CC @gschneider-r7, who originally reported the missing 10.9 support

Add OS X 10.8 and 10.9 NTP fingerprints

---

xml/snmp_sysdescr.xml

Adds/corrects more SNMP sysDescr fingerprints

---

xml/ftp_banners.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/snmp_sysobjid.xml
xml/ssh_banners.xml

Found after using Recog data to fingerprint a private lab.

Miscellaneous SNMP, FTP, SSH and HTTP fingerprints

---

xml/smb_native_os.xml

* Added fingerprints for Windows 10 and Windows 10 Preview Edition

DCA-1216: Windows 10 Fingerprint

---

xml/ssh_banners.xml

There were several catch-all OpenSSH fingerprints that were resulting in us only getting very generic versions from some OpenSSH installations.  I've removed those and updated all of the Ubuntu and Debian fingerprints I could find.
I also ran this PR through a set of Sonar data for 22/TCP from earlier this year.  As I expected, we actually lose quite a bit of coverage.  Without this PR, we miss 76021 out of 78603 unique banners.  With this PR, we miss 77494 out of 78603.  So, neither are especially good, but now we are worse in terms of overall coverage but it will now give us a chance to track down all of the banners that had previously been matching these catch-alls and see if we can do better.
/CC @gwiseman-r7

Improve Debian and Ubuntu OpenSSH fingerprints

---

xml/ftp_banners.xml

Relevant: https://github.com/rapid7/metasploit-framework/pull/5542

Add tnftpd;  Add generic;  Start better multiline support

---

CONTRIBUTING.md

To the best of my knowledge, nobody and nothing is actually using the Github releases.  Nexpose stuff was, at one point, but not any more.  Lets just remove it since it is currently a manual and often forgotten step.
/CC @todb-r7 @hmoore-r7 for any possible metasploit-y questions

Remove documentation on github releases

---

lib/recog/fingerprint/regexp_factory.rb
lib/recog/version.rb
xml/ftp_banners.xml

This patch fixes a regression where MULTILINE was specified, but REG_MULTILINE was needed.

Fix the use of MULTILINE

---

xml/snmp_sysdescr.xml
xml/ssh_banners.xml

It was reported that some fingerprints were missing the appropriate `os.product` and I corrected the two instances.  While here I also made the `os.device` for HP iLO more consistent with what is done elsewhere and similarly with Comware.
/CC @alynn71

Add missing OS for iLO using SNMP and OpenVMS using SSH

---

COPYING
LICENSE

I like this format a lot because it means that I don't have to read the
entire LICENSE every time just to remember if it's BSD 3-clause,
2-clause, MIT, or whatever (they're all really similar). Also, someday,
we might want to package it in a machine readable format, so might as
well get on the stick with that now.

Use Debian-format machine readable license

---

xml/http_servers.xml

Newer versions of Oracle containers use a slightly different format that at least in the one example I found does not include a version.  Aspen is a Python based HTTP server.

Improve Aspen and Oracle Containers HTTP fingerprints

---

xml/smtp_banners.xml

Initially the problem was that a SMTP banner like this wouldn't result in an AIX fingerprint:
```
example.com ESMTP Sendmail AIX5.1/8.11.6p2/8.11.0; Fri, 28 Aug 1970 19:42:05 -0800
```
It was still matching and asserting a Sendmail fingerprint but that was wrong.  The root cause was several defects which you can see in my individual commits.

Fix several Sendmail SMTP regular expressions

---

xml/ssh_banners.xml

Corrected a typo for OpenSSH on MikroTik devices and updated RouterOS sshd regex with an example from RouterOS v6.27. Also added the device type for the latter.
Unfortunately the RouterOS version isn't available just from the banner, but I suspect that ROSSH 2.0 could be running on any RouterOS 5.x and 6.x versions.

Update MikroTik RouterOS SSH fingerprints

---

.travis.yml

This may improve performance for tests/builds on Travis-CI. Faster build starts and better caching of dependencies are the high points of this change. I don't believe Recog requires anything that is restricted in the container environment so this should Just Work (:tm:).
See http://docs.travis-ci.com/user/migrating-from-legacy/ for more info.

Enable use of Travis-CI's container infrastructure

---

xml/http_servers.xml

Based on the header `X-POWERED-BY: PHP/5.3.14 ZendServer/5.0`
I don't know what else besides ZendServer could appear in these headers. I also didn't investigate the difficulty (or possibility) of also capturing the ZendServer name and version at the same time as PHP in this fingerprint. I did not see anything that could conflict on this, but I didn't look very hard either. It might be worth looking through scans.io or Sonar data to see if this could be further improved for other situations.
Tests:
```
$ bin/recog_match -f d -c xml/http_servers.xml
PHP/5.3.14 ZendServer/5.0
MATCH: {"matched"=>"PHP", "service.component.product"=>"PHP", "service.component.version"=>"5.3.14", "data"=>"PHP/5.3.14 ZendServer/5.0"}
PHP/4.4.2-1build1
MATCH: {"matched"=>"PHP", "service.component.product"=>"PHP", …
```

Update PHP regex to work with ZendServer string (X-POWERED-BY header)

---

spec/data/smb_native_os.txt
spec/lib/recog/nizer_spec.rb
xml/smb_native_lm.xml
xml/smb_native_os.xml

Fixes #96
Eventually all of the fingerprints in smb_native_os will need to have their counterparts added in smb_native_lm.
Specs pass, tested by locally releasing a newer version of recog with this new fingerprint in it, then using that new version of recog in a local fix for https://github.com/rapid7/metasploit-framework/issues/6021 and saw it also using the SMB Native LM fields for fingerprinting.

Split out SMB Native LM fingerprints

---

xml/http_servers.xml

Adding an additional fingerprint pattern for the Nexpose Security Console that uses a new pattern to be changed in an upcoming release of Nexpose. This pattern is version-less.

Adding support for modern Nexpose fingerprint matching

---

xml/mysql_banners.xml

Changed uses of `\h` to ~~`[a-fA-F\d]`~~ (update: now `[a-f\d]` with case-insensitive flag) since `\h` seems to be a ruby-specific thing and Nexpose could not match with it.
~~Added `os.device` to fingerprints that have OS info.~~
~~Added `os.certainty` to fingerprints that have OS versions. Somewhat arbitrarily chose 0.80 as likely to be useful and not likely to interfere with potentially superior fingerprints from SSH or other services.~~
One thing I wonder about is switching the MariaDB version match group to the 2nd set of numbers, but that probably means lots of edits/new fingerprints to keep compatibility with banners that don't have the 2nd set. **Update 4/13: Done** - I swapped the optional groups around for MariaDB so that 10.x.x versions will capture instead of 5.5.5, but 5.x.x …

Changes to MySQL banners for Nexpose support

---

xml/smb_native_os.xml

Banners for VisionFS and OS/400
According to our code comments VisionFS returns [AR][OS][VFVR] which is arch, os and VisionFS version. The remainder of the visionFS banner contains the "uname -a" output, such as: `[abbrev] [uname -a output...`:
```
i3un0210 UnixWare unixware7 5 7 i386
```
After discussion within the team, we decided to error on the safe side and only match on the [abbrev].
RSpec output:
```rspec
Finished in 53.32 seconds (files took 1.9 seconds to load)
17868 examples, 0 failures
Randomized with seed 64103
/opt/ruby2.2/lib/ruby/gems/2.2.0/gems/simplecov-0.10.0/lib/simplecov/defaults.rb:50: warning: global variable `$ERROR_INFO' not initialized
Coverage report generated for RSpec to /home/jkennedy/rapid7/recog/coverage. 690 / 722 LOC (95.57%) covered.
```

SMB banners for VisionFS and OS/400

---

README.md
lib/recog/fingerprint.rb
lib/recog/fingerprint/test.rb
spec/lib/fingerprint_self_test_spec.rb
xml/ldap_searchresult.xml

This PR adds support for parsing the binary LDAP searchResponse banner. There are 55 new fingerprints with 68 total tests. 
It also adds the `_encoding` attribute to `example` fingerprint elements to allow example strings to be base64 encoded. 
For example:
````xml
<example _encoding="base64">
dGllczGEAAAAlQQWMS4yLjg0MC4xMTM1NTYuMS40LjgwMAQuZGF0YS5yZW1vdmVkLjCE
AAAAKAQdZG9tYWluQ29udHJvbGxlckZ1bmN0aW9uYWxpdHkxhAAAAAMEATc=
</example>
````

Add Recog support for LDAP searchResponse and encoded examples

---

xml/ssh_banners.xml

This is just a start, will push more missing SSH banners as I go.  Current questions: 
- Rasbian is for the Raspberry Pi but as-is this isn't mentioned in the fingerprint.  Where should it go?  And should we add a new "IoT" category or family? 
- HipServ is a home NAS to store media is there a better family for that?  Otherwise I've called it a Router...

Add missing OpenSSH and HipServ SSH fingerprints

---

xml/ftp_banners.xml

This PR adds banner detection from Vermillion FTP Daemon - this is to allow 2 new vuln checks to fire: https://github.com/rapid7/nexpose-content/pull/1248

DCA-6545: Added Vermillion FTPD fingerprint

---

xml/ftp_banners.xml

This update is based on processing the Scans.io database for ftp banners fro 2016.10.31.  It also includes adjustments to existing fingerprints to add additional example tests and/or additional data.

Fingerprint update: 2016.11 - ftp.banner

---

lib/recog/fingerprint.rb
spec/lib/fingerprint_self_test_spec.rb
xml/ftp_banners.xml

An internal source pointed out that one of the `vsftpd` fingerprints had a param with a position of 0 (indicating that it wasn't a capture) but which didn't have a value either.
` <param pos="0" name="service.version"/>`
I've added support for detecting this issue with `bin/recog_verify`.  I've also added support for detecting this as well as the issue where a param is a capture but has a value to Recog's RSpec tests.
Example output from `bin/recog_verify`
```bash
$ bin/recog_verify xml/ftp_banners.xml 
WARN: 'ProFTPD on a wired Linksys device' has no test cases
FAIL: 'vsFTPd (Very Secure FTP Daemon) error message's service.version is at zero pos but doesn't specify a value
WARN: 'Nepenthes honeypot' has no test cases
FAIL: 'FTPD on a ZyXEL (Huawei rebrand) WiMax WAP's hw.family is a …
```

Improve validation of fingerprint param values

---

xml/ftp_banners.xml

This PR adds a fingerprint for QPC Software's FTP Server which was bundled with the following utility packages for Windows systems:
- QVT/Net
- QVT/Term
- AVT/Term
The contents of the packages differs but the FTP Server is common across all of them. Could not obtain the AVT/Term utility package as these programs have been obsolete for many years and this flavour seemed rare/non-existent, however the FTP Daemon bundled with QVT/Net 4.1 and QVT/Term 5.1 responded with the banners:
`qpc-qvtnet FTP server (QVT/Net 4.1) ready.`
`qpc-qvtnet FTP server (QVT/Net 5.1) ready.`
...respectively (`qpc-qvtnet` being the host name of the Windows XP VM).

Add fingerprint for QPC Software QVT/Net FTP Server

---

xml/http_cookies.xml

Adds a fingerprint for [Moodle](https://moodle.org/) from the Session cookie returned by the service.

Add fingerprint for Moodle

---

xml/http_cookies.xml

Authenticated HTTP and Cookie HTTP Moodle fingerprints' vendor updated to "Moodle" to be consistent across all 3 methods of fingerprinting Moodle Web App.
Moodle fingerprint vendor was inconsistent across the 3 fingerprinting threads for Moodle. The Authenticated Web App fingerprinter was also asserting a component FP, rather than a Software FP and therefore, the Moodle content would not fire (as it was looking for a Product fingerprint)
```
2017-04-21T15:38:28 [INFO] [Thread: moodle-linux-u.vuln.lax.rapid7.com:80/TCP] [Site: a] Asserting Fingerprint [[certainty=0.9][description=Moodle][family=Moodle][product=Moodle][vendor=Moodle][version=null]]
```

Fix inconsistency in Moodle fingerprint vendor

---

xml/snmp_sysdescr.xml

Adding family to Cisco NX-OS and SAN fingerprint
SNMP fingerprinting is missing os.family for Cisco NX-OS and SAN.
```
SystemFingerprint [[architecture=null][certainty=0.85][description=Cisco NX-OS 4.1(3a)][deviceClass=Switch][family=NX-OS][product=NX-OS][vendor=Cisco][version=4.1(3a)]] source: SNMP
```

Add family for Cisco NX-OS and SAN fingerprint

---

xml/http_servers.xml

Adding banner detection from Intel AMT's HTTP web management console running on `tcp/16992` and `tcp/16993` (HTTPS)

Adding banner detection for Intel AMT

---

xml/x11_banners.xml

The X11 protocol includes a vendor field when access is successfully
granted. New fingerprints based off this vendor field have been added.

Add fingerprints for X11 banners

---

xml/smb_native_lm.xml
xml/smb_native_os.xml

This improves Recog's ability to fingerprint Samba and Windows-based SMB endpoints via the native LM and OS responses.

Improve SMB fingerprints

---

xml/smtp_banners.xml

This PR adds examples and moves some of the existing examples from the description field into the `example` tags.  It also improves the regex of some of the patterns so as to reduce the number of fingerprints that are required.

smtp_banners: improve examples, remove duplication

---

features/verify.feature
lib/recog/fingerprint.rb
xml/operating_system.xml

Adaptive Security uses recog to parse operating systems from outside sources (Azure, Active Directory, etc) when importing assets into Nexpose. Other sources have minor variations in the way they represent OS names (e.g. starting with "SLES" instead of "SUSE SLES", or "Ubuntu-14.04" instead of "Ubuntu 14.04"). Change the OS fingerprinting to also match these minor variations.

More robust operating system parsing

---

xml/ftp_banners.xml
xml/operating_system.xml

As indicated in #138 the use of `\h` is a special feature of Ruby's regex engine. For other languages and runtimes it causes the matches to fail since it has a different meaning. I replaced all occurrences that I could find.
Additionally I fixed the Windows OS catch-all regex which had really bad backtracking performance, especially in Java where it would take 20-30 seconds to match (or not match) for a single string. Since it is super generic anyway I got rid of the attempt at capturing a version for it as well.

Convert hex regex patterns to be language-agnostic and fix bad Windows OS catch-all regex

---

xml/operating_system.xml

Sometimes all that is available is the windows version (e.g. "Windows 6.1" or "Windows 10.0"). This can be partially matched, for instance "Windows 6.1" is either Windows 7 or Windows Server 2008.

Match windows by version

---

xml/ftp_banners.xml
xml/ntp_banners.xml
xml/operating_system.xml
xml/snmp_sysdescr.xml

Previously ntp banners for Solaris had their os.product value set to 'Solaris' , however the version was being set to the SunOS version which is different from the Solaris version, see: https://en.wikipedia.org/wiki/Solaris_(operating_system)#Version_history
Due to the first digit of the Solaris version being different from the SunOS version I have created  separate fingerprints for all regex matching SunOS/5.0 -> SunOS/5.6, as their versions have to be hard coded, for example the following regex pattern:
`  <fingerprint pattern="^.*processor=&quot;([^ ]+)&quot;,.*system=&quot;SunOS/5.1&quot;" flags="REG_DOT_NEWLINE,REG_ICASE">
`
Has its os.version set :
`<param pos="0" name="os.version" value="2.1" />
`
From SunOS/5.7 and upwards the Solaris version is just the final digit from the SunOS …

Fix solaris version matches from ntp

---

xml/snmp_sysdescr.xml

Adds fingerprinting of pfSense firewall devices/virtual appliances via the SNMP banner
pfSense is a fairly prevalent firewall/gateway device that currently has ~23 CVEs against it
```
cmccrisken@ciaran-dev:~/rapid7/cmccrisken-r7/recog (git: master)$ bin/recog_verify xml/snmp_sysdescr.xml 
WARN: 'Castelle FaxPress' has no test cases
WARN: 'NetportExpress Print Server' has no test cases
WARN: 'Lexmark C760 Color Laser Printer' has no test cases
WARN: 'Red Hat Enterprise Linux 4 Update 3' has no test cases
SUMMARY: Test completed with 2931 successful, 4 warnings, and 0 failures
```
```
2017-06-29T19:43:25 [INFO] [Thread: 10.4.28.201:161/UDP] [Site: pfs2] Asserting SystemFingerprint [[architecture=amd64][certainty=0.9][description=FreeBSD …
```

Added fingerprinting of pfSense (and bsnmpd) via SNMP

---

xml/dns_versionbind.xml

This PR adds support for fingerprinting text string response from a DNS version.bind request.
For example, the string `dnsmasq-2.76-1-ubnt2` emitted by the command below:
```
$ nslookup -type=txt -class=chaos VERSION.BIND <dns_server> | grep VERSION.BIND | cut -d\" -f2
dnsmasq-2.76-1-ubnt2
```
There are currently 49 fingerprints in the submission.  These fingerprints have been grouped by product and roughly ordered by frequency of occurrence based on Project Sonar studies of the public Internet.
**Note:** Per RFC the DNS queries should be case insensitive.  Microsoft doesn't follow this RFC and so Microsoft Windows DNS servers will respond to `version.bind` but not to `VERSION.BIND` requests.  Also, by default version responses are disabled on modern Microsoft Windows DNS servers.

Add support for DNS version.bind responses

---

xml/dns_versionbind.xml

This fixes an edge case when Recog content is used in isolation in systems whose regular expression libraries do not support a lack of a lower bound on a count of a characters, like `\d{,2}`, which should match 1-2 digits.

Specify lower bound on character counts

---

.travis.yml

Avoid duplicating travis builds on tag pushes and PRs from origin branches. This doesn't really do anything for us directly, but it is nice to not spend extra cycles unnecessarily on a free service.

Limit branch builds to master branch only

---

xml/smtp_banners.xml

The primary purpose of this commit is to improve coverage of Exim in `xml/smtp_banners.xml`.
In addition to this I've added multiple examples for some other product fingerprints that were missing them. During this I found multiple fingerprints that didn't match the examples found in the description and/or in the wild.  These were fixed as well.

Improve Exim coverage, add general examples

---

xml/ssh_banners.xml

This PR updates the coverage of `xml/ssh_banners.xml` using data from Project Sonar's SSH study on 2017.11.30.  The most significant changes were from adding coverage of Debian Stretch and covering OpenSSH on Ubuntu and Debian where the package version was displayed but the OS release was not, for example `OpenSSH_7.6p1 Ubuntu-2`. The latter had in some cases been misidentified as a certain version of Debian or Ubuntu so overall accuracy has been improved.
In total 484,768 previously unidentified banners are now matched.
Significant changes:
- New fingerprints:
- OpenSSH running on Debian 9.x (stretch) - 163,762 matches
- OpenSSH backport running on Debian 7.x (wheezy) - 36,937 matches
- OpenSSH running on Debian (unknown release) - 126,562 matches
- OpenSSH running on Ubuntu (unknown …

ssh_banners.xml: Update using Project Sonar data from 2017.11.30

---

xml/mysql_banners.xml

This should detect MariaDB on Jessie as per the current official container on Docker Hub.

Add Debian 8.0 (jessie) MariaDB fingerprint

---

xml/smtp_banners.xml

This PR updates the coverage of `xml/smtp_banners.xml` using data from Project Sonar's SMTP 25/tcp study on 2017.11.30.  Additionally, there was significant reorganization and cleanup of the file.
**Note: Due to effort to cleanup description lines (remove duplicates, remove multilines, provide context, standardize format) almost every value for `<description>` has changed. This *will* impact the value returned as `matched`.**
Original fingerprint count: 129 
Original fingerprint count: 133
- Improved the accuracy and/or flexibility of multiple fingerprints.
- Changed *ALL* instances of `flags="REG_ICASE`  to an inline flag (`(?i:`) in order to make the regex compatible with more languages.
- Implemented fingerprint examples for those fingerprints where examples could be found. This …

smtp_banners: Update using Project Sonar data from 2017.11.30 and 2018.04.05

---

xml/dns_versionbind.xml
xml/operating_system.xml
xml/smtp_banners.xml

This change corrects two typos and removes two negative look aheads, allowing these expressions to be parsed by the Go standard library 'regexp' engine.

Small regexp fixes for Go compatibility

---

xml/ftp_banners.xml

Comes from an FTP banner seen on shodan here is the full output (with response codes)
`
220-Amazon Linux AMI release 2016.09
220-Kernel \r on an \m
220-
220
530 Permission denied.
530 Please login with USER and PASS.
211-Features:
EPRT
EPSV
MDTM
PASV
REST STREAM
SIZE
TVFS
UTF8
211 End`
nexpose PR - https://github.com/rapid7/nexpose/pull/5573

Amazon Linux AMI fingerprinting via ftp banner

---

.rake_tasks~
xml/mysql_banners.xml

Adds fingerprinting support for MariaDB MaxScale 
MariaDB Maxscale is a popular database proxy and adding it will increase coverage of the MariaDB line of products

Adding maria db max scale banner support

---

spec/lib/fingerprint_self_test_spec.rb
xml/smtp_banners.xml

Working on something else recog related and it tripped over duplicate `param` attributes.  This addresses the specific issue.  I added a unit test too, however it doesn't seem to detect the problem when used against current `master`.

Correct duplicate params in SMTP banner fingerprints

---

xml/snmp_sysdescr.xml

Based off of PR #166  this accounts for the changes landed today and adds back (after today's changes) an additional test that includes the comma.

Adjusted PR166 for Juniper FP in snmp_sysdescr.xml

---

xml/smtp_banners.xml
xml/smtp_ehlo.xml
xml/smtp_expn.xml
xml/smtp_help.xml
xml/smtp_vrfy.xml

The original code from which these recog fingerprints were derived expects Cisco PIX fingerprints to be for OS rather than service, which aligns with what is done in CPE.  Why these were done with service looks like to be an oversight.

Correct Cisco PIX fingerprints to use OS rather than service fingerprint

---

remap.json
xml/http_servers.xml

This PR is a banner update of the `http_servers.xml` file using data from a Project Sonar survey of HTTP on port 80 that occurred on 2018.08.13.
There are additional tweaks to support CPE generation as well as add `hw.device` and similar fields where possible.
*Note:* I am unsure as to why the CPE ordering changed.

Banner update: HTTP - 2018.08.13

---

remap.json
xml/apache_modules.xml

This is definitely not complete, but adds fingerprinting for 141 Apache HTTPD modules owned/managed by the Apache project.  It also adds a few others.  Automation found 14 CPEs.  NVD isn't consistent on when they properly indicate the vulnerable Apache module in CPE.  We can update it over time.

Add fingerprinting for Apache modules

---

xml/telnet_banners.xml

Initial commit of TELNET fingerprint coverage.  This should be viewed with a very critical eye.
Processes leveraging the fingerprints *should* remove TELNET options control codes as well as strip CR, LF, and other whitespace from both ends of the banner.
A couple notes. 
1. Regex for leading CR/LF characters and trailing space characters has been left in place to enable a current project.  This will be removed the near future.
2. TELNET banners most often contain CR and LF. In order to properly create testable examples I've base64 encoded the banners.  The pattern I am using is a comment with the original banner containing escaped CR/LF followed by the encoded banner.
```xml
<example _encoding="base64" os.version="5.2">TWlrcm9UaWsgdjUuMg0KTG9naW46Cg==</example>
```

TELNET: Initial commit

---

lib/recog/fingerprint.rb
spec/lib/recog/fingerprint_spec.rb
xml/http_servers.xml

When we added the CPE functionality to recog xml/product, we also introduced the concept of value interpolation such that if you had a `fingerprint` with a `params` like:
```
...
<param pos="1" name="service.component.version"/>
<param pos="0" name="service.component.cpe23" value="cpe:/a:redhat:stronghold:{service.component.version}"/>
...
```
The idea is that the value of `service.component.cpe23` would be composed of `cpe:/a:redhat:stronghold:` and the value of `service.component.version` which is extracted at fingerprint match time.
This PR adds the necessary functionality to recog "product" to enable this.  I updated one simple `param` as an example of this.  I added a check/test for this in `Fingerprint` itself, but part of me feels like it should be in the self test spec instead. …

Support interpolation of fingerprint values

---

lib/recog/fingerprint.rb
spec/lib/fingerprint_self_test_spec.rb

Two big things are changing here:
* Rather than checking for and, if necessary, attempting interpolation on every emitted fingerprint value, determine which need it in advance, and what values each interpolates.  Among other things, it prevents this:
```
$  echo "X1 NT-ESMTP Server {FOO} (IMail 6.06 EVAL 11347-1)" | ./bin/recog_match xml/smtp_banners.xml
/Users/jhart/rapid7/recog/lib/recog/fingerprint.rb:122:in `block in match': Invalid use of nil interpolated value FOO in non-cpe23 fingerprint param host.name (RuntimeError)
from /Users/jhart/rapid7/recog/lib/recog/fingerprint.rb:98:in `each_pair'
from /Users/jhart/rapid7/recog/lib/recog/fingerprint.rb:98:in `match'
from /Users/jhart/rapid7/recog/lib/recog/matcher.rb:34:in `block (3 levels) in match_banners'
from …
```

Refactor interpolation

---

xml/sip_banners.xml

This is by no means exhaustive.  Using the most recent Sonar SIP data from https://opendata.rapid7.com/sonar.udp/, I found the most common server headers and added coverage for many of them.

Improve SIP fingerprints

---

xml/http_cookies.xml

These are everywhere but don't have anything else in the header that makes them easily identifiable as a Cisco ASA / VPN except for the `Set-Cookie` headers:
```
$   lwp-request  -sd -m GET -UuSe https://some-asa |grep Set-Cook
Set-Cookie: webvpn=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; secure
Set-Cookie: webvpnc=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; secure
Set-Cookie: webvpn_portal=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; secure
Set-Cookie: webvpnSharePoint=; expires=Thu, 01 Jan 1970 22:00:00 GMT; path=/; secure
Set-Cookie: webvpnlogin=1; path=/; secure
```

Add Cisco ASA/VPN HTTP cookie fingerprint

---

xml/upnp_banners.xml

In looking over the most recent UPnP results from sonar, I observed the following CPEs:
```
count  cpe
-------  --------------------------------------
16141  cpe:/o:canonical:ubuntu_linux:7.10
5012  cpe:/o:canonical:ubuntu_linux:lucid
2233  cpe:/o:canonical:ubuntu_linux:10.10
314  cpe:/o:canonical:ubuntu_linux:9.04
294  cpe:/o:canonical:ubuntu_linux:10.04
37  cpe:/o:canonical:ubuntu_linux:jaunty
36  cpe:/o:canonical:ubuntu_linux:maverick
28  cpe:/o:canonical:ubuntu_linux:hardy
20  cpe:/o:canonical:ubuntu_linux:oneiric
14  cpe:/o:canonical:ubuntu_linux:karmic
12  cpe:/o:canonical:ubuntu_linux:14.04
7  cpe:/o:canonical:ubuntu_linux:13.04
6  cpe:/o:canonical:ubuntu_linux:precise
4  cpe:/o:canonical:ubuntu_linux:natty
3  cpe:/o:canonical:ubuntu_linux:12.10
2 …
```

Refactor Ubuntu UPnP fingerprints to avoid non-numeric versions

---

xml/ssh_banners.xml

Fingerprinting for the libssh SSH library. 
The banner formats are defined [here](https://git.libssh.org/projects/libssh.git/tree/include/libssh/priv.h?h=libssh-0.6.0#n126) and [here](https://git.libssh.org/projects/libssh.git/tree/include/libssh/priv.h?h=libssh-0.8.0#n155).

Add fingerprinting for libssh

---

xml/telnet_banners.xml

We have improved recog's telnet coverage by adding various fingerprints that were previously missing. Most notably the addition of Red Hat, Fedora, AIX and SuSE telnet coverage, as well as adding to the already Cisco coverage that was previously being used.

Improve telnet fingerprinting

---

cpe-remap.yaml
xml/mdns_device-info_txt.xml

This PR adds fingerprints for `osxvers=` and `model=` strings.  This new coverage, while not comprehensive, add significant coverage for Apple devices.  The information was pulled from network captures from multiple locations.
I also added a value to `cpe-remap.yaml` which converts the value for Apple iOS to the standard CPE value of `iphone_os`.
Note:  The CPE fields are reordered in the original macOS fingerprints.  I don't know why, I used the same command as before.
```
./update_cpes.py mdns_device-info_txt.xml official-cpe-dictionary_v2.3.xml cpe-remap.yaml  && \
xmllint --format --noblanks official-cpe-dictionary_v2.3.xml > official-cpe-dictionary_v2.3.xml.bak && \
mv official-cpe-dictionary_v2.3.xml.bak official-cpe-dictionary_v2.3.xml 
```
Testing was performed via `rspec` locally …

OCTO-1870 MDNS device-info improvement

---

xml/hp_pjl_id.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/pop_banners.xml
xml/snmp_sysdescr.xml
xml/upnp_banners.xml

This PR is the first pass at replacing the use of `flags=`in fingerprints with inline flags. The changes here should make the fingerprints more portable across languages.
This PR covers most fingerprint databases but there are a couple that were deferred since nearly every fingerprint in those files have one or more flags and so would be easier to review if handled individually. 
Note: I've tried to avoid replacing `flags="REG_DOT_NEWLINE"` with `(?m)` as the behavior of `(?m)` is different across languages.  See https://www.regular-expressions.info/modifiers.html
Local testing via `rspec` and Jenkins testing of the same.

RCG-22: Replace Recog flags w/ inline flags

---

.github/ISSUE_TEMPLATE/fingerprint_request.md

This adds a new issue template specifically for requesting fingerprint coverage.
After adding the other issue templates I realized that they might be overwhelming for someone who just wants some new fingerprint added. Ultimately I want this repo to be as accessible as possible in order to encourage more community participation.

Add new issue template for fingerprint requests

---

cpe-remap.yaml
xml/http_servers.xml

This improves the fingerprinting of Squid by:
* Making the existing regex more case-insensitive
* Adding a fingerprint for when Squid presents no version
* Add a vendor to all Squid fingerprints
* Add Squid CPE support
Squid is a popular web cache/proxy with millions of endpoints exposed on the public Internet.
The existing examples are tested automatically.

Improve Squid fingerprinting

---

xml/http_servers.xml

This adds HTTP fingerprints for AWS S3, Snowball, Drive and SimpleDB, which are known to listen on the public Internet in a variety of capacities.
AWS.
Existing and new tests.

Add HTTP fingerprints for some Amazon products

---

spec/lib/fingerprint_self_test_spec.rb
xml/mysql_banners.xml
xml/snmp_sysdescr.xml

Currently many fingerprints assert the device type through one or more of `os` and `hw`.  Only two use both but with inconsistent values and this seems like a mistake.  So, I've corrected the two problematic fingerprints and put a test in place to enforce this going forward.
See description
Existing tests pass, new tests pass and were used to catch the two problematic fingerprints in the first place.

Ensure consistency of os.device and hw.device when both present

---

xml/mdns_device-info_txt.xml

Adding additional MDNS fingerprints for Apple products (iPad/Macbook/Pro)
Internal capture showed these missing. 
Manual local testing from capture logs. 
Verify with 
- https://support.apple.com/en-us/HT201300
- https://www.theiphonewiki.com/wiki/J121AP
- Adding fingerprints

Add more fingerprints for MDNS Apple products

---

xml/http_cookies.xml

Improve HTTP cookie fingerprinting for Cisco ASA and Citrix Netscaler
More fingerprints, there are lots of these on the public Internet.
GPRs, `bundle exec rspec` passes locally

Improve HTTP cookie fingerprinting for Cisco ASA and Citrix Netscaler

---

xml/http_wwwauth.xml
xml/snmp_sysdescr.xml
xml/telnet_banners.xml

This adds a large number of fingerprints related to the HTTP `WWW-Authenticate` header used during authentication.  These new fingerprints were taken from a variety of Sonar studies of HTTP endpoints.  This includes a lot of CPE equipment, cameras, routers, etc, plus general cleanup.  Individual chunks can be seen in the specific commits.
I've tried to stay as consistent as possible while not introducing any net-new problems here.  Also note that I'm not necessarily cleaning up all problems while here.  This was just a run through the top 100 or so big clusters of things I know we don't fingerprint.
I've added examples for everything I added, and they all pass.

Improve HTTP WWW-Authenticate header fingerprinting

---

xml/smb_native_lm.xml
xml/smb_native_os.xml
xml/snmp_sysdescr.xml
xml/upnp_banners.xml

This updates the SMB fingerprints for various products as seen in recent Sonar studies.
More fingerprints, higher quality.
GPRs with examples

Add SMB fingerprints for Mikrotik, Netreon, EMC Cellera and Apple devices

---

xml/sip_banners.xml
xml/sip_user_agents.xml
xml/ssh_banners.xml
xml/upnp_banners.xml

Using recent Sonar data for SIP, SSH and UPnP, I've updated the coverage of Huawei products in recog.  It was something I had meant to come back to after recent Huawei Home Gateway / Echolife updates in similar/other databases.
@brudis-r7
Better fingerprints
GPR

Improve Huawei coverage in SIP, SSH, UPnP

---

xml/http_servers.xml

Added a new fingerprint to http server header field, based on a server header I saw in the wild:
awselb/2.0
Links to forums to people who have also seen the header:
https://forums.aws.amazon.com/thread.jspa?threadID=239290
https://www.reddit.com/r/aws/comments/9rl50j/elb_possible_to_suppress_server_awselb20_header/
Seen in the wild thought it be a small add.
Locally:
```
$ echo 'awselb/2.0' | ./bin/recog_match xml/http_servers.xml
MATCH: {"matched"=>"Amazon Elastic Load Balancing", "service.vendor"=>"Amazon", "service.product"=>"Elastic Load Balancing", "service.version"=>"2.0", "service.protocol"=>"http", "fingerprint_db"=>"http_header.server", "data"=>"awselb/2.0"}
```
& results of  ```rake tests```
```
9 scenarios (9 passed)
20 steps (20 passed)
0m3.847s
```
Added a new xml snippet
- …

Add AWS ELB fingerprint

---

xml/ftp_banners.xml
xml/html_title.xml
xml/http_servers.xml
xml/sip_user_agents.xml
xml/smb_native_lm.xml

This adds a new fingerprint database to recog that can be used to fingerprint based on the `Title` element present in HTML HTTP responses.  This adds just a few examples to get approval on the general idea as suggested by @hdm and others and we can add more in future PRs.
This provides some great opportunities to fingerprint devices where other HTTP methods suffer.  
I've added tests for everything new.

Add fingerprinting for HTML titles

---

xml/html_title.xml

This adds several more fingerprints based on HTML titles, including cpanel, IIS, Apache, FRITZ, Tomcat, Philips Hue, Sonicwall, Ubiquiti, ASUS, Plesk and more.  See commits for specifics.
GPR

Add more fingerprints based on HTML titles

---

xml/x509_issuers.xml
xml/x509_subjects.xml

This is a first run at fingerprints for TLS issuer and subject fields. I plan to keep updating this for a while, but would appreciate any feedback on the current state. Coverage-wise, this is about 50% of the systems that I am trying to match, but that doesn't include any Sonar scans.

TLS issuer and subject fingerprints

---

xml/http_servers.xml
xml/mysql_banners.xml
xml/smtp_banners.xml
xml/ssh_banners.xml
xml/x509_subjects.xml

This PR:
- Reduces the number of duplicate `description` fields. Duplicates in this field can cause issues when processing large number of banners and generating metrics on the fingerprint matches.
- Cleans up a few multi-line `description` fields, these are undesirable for similar metrics reasons.
- Adds a few `service.version` tests for `example` fields. Every regex should have every extracted value tested at least once. One of these new tests found an error in the regex for a fingerprint.
Expect a few more of these as time permits. I'm trying to avoid asking folks to review a wall of changes all at once.
These changes improve the usability of `recog`
`rspec`

RCG-30: Description deduplication

---

xml/apache_os.xml
xml/ftp_banners.xml
xml/h323_callresp.xml
xml/http_cookies.xml
xml/http_wwwauth.xml
xml/imap_banners.xml
xml/ldap_searchresult.xml
xml/ntp_banners.xml
xml/pop_banners.xml
xml/smb_native_os.xml
xml/smtp_banners.xml
xml/smtp_debug.xml
xml/smtp_ehlo.xml
xml/smtp_expn.xml
xml/smtp_help.xml
xml/smtp_noop.xml
xml/smtp_quit.xml
xml/smtp_rcptto.xml
xml/smtp_vrfy.xml

This PR is very similar to the previous PR.  It:
- Reduces the number of duplicate `description` fields. Duplicates in this field can cause issues when processing large number of banners and generating metrics on the fingerprint matches.
- Cleans up a few multi-line `description` fields, these are undesirable for similar metrics reasons.
- Adds a few `service.version` tests for `example` fields. Every regex should have every extracted value tested at least once. One of these new tests found an error in the regex for a fingerprint.
- Adds some examples and relocates some examples from the `description` field.
Most of the remaining changes are in the `snmp_sysdescr.xml` and I'll handle them as well as the `rspec` tests in the next PR. 
These changes improve the usability of `recog`
`rspec`

RCG-30: Description / Example cleanup

---

spec/lib/fingerprint_self_test_spec.rb
xml/snmp_sysdescr.xml
xml/snmp_sysobjid.xml

This PR is very similar to the previous two PRs.  It:
- Addresses the remaining duplicate `description` fields. Duplicates in this field can cause issues when processing large number of banners and generating metrics on the fingerprint matches.
- Adds a test to ensure that every `description` field is unique.
- Adds a few `service.version` tests for `example` fields. Every regex should have every extracted value tested at least once.
- Hard codes certain param values where the regex was capturing a fixed value, for example - `Something (Model X Switch) .*`
- Combines a few fingerprints where only a minor tweak to the regex was required.
- Fixes a few copy-pasta errors
When reworking the descriptions I tried to indicate what was different between them. In some cases it was non-obvious or …

RCG-30: Final description cleanup + test

---

spec/lib/fingerprint_self_test_spec.rb
xml/ftp_banners.xml
xml/http_servers.xml
xml/mysql_error.xml
xml/operating_system.xml
xml/snmp_sysdescr.xml
xml/x509_subjects.xml

This PR removes duplicate `example` entries and adds an `rspec` test to detect when they are added in the future.
Here is an example of the output when the new test fails due to a duplicate `example`:
```
Failures:
1) Recog::DB#http_servers.xml (?i-mx:^Netgear\/\S+ UPnP\/\S+ miniupnpd\/(\S+)$) doesn't have a duplicate examples
Failure/Error: fail "'#{fp.name}' has duplicate example '#{example.content}'"
RuntimeError:
'Netgear DG834G or WNDR3300 WAP UPnP Server' has duplicate example 'Netgear/1.0 UPnP/1.0 miniupnpd/1.0'
2) Recog::DB#http_servers.xml (?-mix:^lighttpd(?:\/(\d[\d.]+))?.*$) doesn't have a duplicate examples
Failure/Error: fail "'#{fp.name}' has duplicate example '#{example.content}'"
RuntimeError:
'Lighttpd' has duplicate example 'lighttpd/1.4.16'
3) …
```

RCG-30: Remove duplicate examples and add test

---

xml/http_servers.xml

This PR:
- Addresses the fact that Jetty changed hands / stewardship from Mort Bay to Eclipse in version 7. By fixing this we ensure that the CPEs that are generated are correct and are likely to be able to use to match vulnerabilities.
- Collapses two fingerprints into one by taking into account that some versions have non-decimals in them (`4.2.x`) and that some version strings left off the trailing `)` in the info section.
- Adds capture tests for the examples.
```
$ echo 'Jetty(9.4.z-SNAPSHOT)' | bin/recog_match xml/http_servers.xml 
MATCH: {"matched"=>"Eclipse Jetty", "service.vendor"=>"Eclipse", "service.product"=>"Jetty", "service.family"=>"Jetty", "service.version"=>"9.4.z-SNAPSHOT", "service.cpe23"=>"cpe:/a:eclipse:jetty:9.4.z-SNAPSHOT", "service.protocol"=>"http", …
```

Fix Jetty vendor and fingerprints

---

xml/http_servers.xml
xml/smtp_banners.xml

This PR add specific IIS 10.0 entries into the HTTP Server and SMTP databases. IIS 10 is found on both Windows Server 2016 and Server 2019. SMTP provides us a build number which can be use to determine if the OS is Win 2016 or 2019.
Per Microsoft:
Reference notes (for me):
https://docs.microsoft.com/en-us/windows/release-information/
General fingerprint improvements
Improved fingerprints

Win 2019 adjustments

---

xml/mdns_device-info_txt.xml

Coverage for 2018 Mac mini and 2019 15" MacBook Pro
Minor fingerprint addition
rspec and using the recog-go harness
- Support for newer MacBook Pro and Mac mini devices.

Adds 2018 Mac mini and 2019 MBP to MDNS

---

xml/ftp_banners.xml

This PR adjusts an FTP fingerprint so as to no longer match on empty strings.
```shell
echo '' |  ./bin/recog_match xml/ftp_banners.xml 
MATCH: {"matched"=>"Generic FTP fingerprint without a hostname", "service.protocol"=>"ftp", "fingerprint_db"=>"ftp.banner", "data"=>""}
```
```shell
echo '' |  ./bin/recog_match xml/ftp_banners.xml 
FAIL: 
```
The trade off is that we no longer match `Server Ready`. Given that this banner is not product or service specific I consider this an acceptable trade off. Our most Sonar data set from May 1 showed 0 hits for this banner.
rspec

FTP: stop matching empty banners

---

xml/mdns_device-info_txt.xml

This PR includes a number of new Apple MDNS fingerprints (laptops, desktops, servers, devices, mobile phones, tablets, TVs, and homepod).
This resolves missing fingerprints for a wide range of Apple products.
Use of rspec, recog_verify, and testing against real device fingerprints.
- Support for a wide range of Apple devices

Additional Apple devices

---

xml/snmp_sysdescr.xml

Updated the SonicOS fingerprinter so we can capture the hardware model version separately from the hardware model name
New Fingerprint matches all examples given as expected:
Match # | Group index | Start index | End index | Group content
-- | -- | -- | -- | --
1 | 0 | 0 | 58 | SonicWALL SuperMassive 9200 (SonicOS Enhanced 6.2.5.3-35n)
1 | 1 | 10 | 22 | SuperMassive
1 | 2 | 23 | 27 | 9200
1 | 3 | 46 | 57 | 6.2.5.3-35n
Rake tests pass
```
9 scenarios (9 passed)
20 steps (20 passed)
0m2.782s
```

DCA-17412: Updated SonicOS recog fingeprint

---

xml/ftp_banners.xml
xml/snmp_sysdescr.xml

Might be better to have an example fingerprint from Phaser 3635MFP instead of just 3300 - couldn't find any on Shodan, maybe sonar could help us out on Monday if we want to boost confidence.
```
Software releases are available for:
WorkCentre 3335/3345 on 9/6/19
Xerox B1022/B1025 on 9/19/19
Xerox Phaser 3635MFP on 10/2/19
```
https://security.business.xerox.com/en-us/news/wind-river-vxworks-ipnet-tcp-ip-stack-vulnerabilities/
Rake Tests pass after latest commit `be696ff`:
```
9 scenarios (9 passed)
20 steps (20 passed)
0m2.787s
```

DCA-17416: Updated Xerox recog fingeprint for Urgent/11

---

xml/ftp_banners.xml
xml/ssh_banners.xml

This PR cleans up a few banners and adds some new ones:
* ftp:
* 3 ProFTPD variants
* 1 TP-Link banner
* 3 banners for FTP services providers (Amazon, DreamHost, home.pl)
* ssh:
* OpenSSH for Windows
* WeOnlyDo
These banners provide more coverage for several banners seen in the wild that have not already been fingerprinted.
I ran `rspec`, `rake tests` and `recoc_verify` none of which reported errors.

Add a few ftp and ssh banners and a little cleanup

---

features/data/successful_tests.xml
features/data/tests_with_warnings.xml
features/verify.feature
lib/recog/fingerprint.rb
spec/data/verification_fingerprints.xml
spec/lib/recog/fingerprint_spec.rb

Added a method `verify_tests_have_capture_groups` to `lib/recog/fingerprint.rb` which loops over the parameters provided by a fingerprint, finds the parameters that are defined by capture groups, and then raises a warning if there is not at least one example for each parameter defined by a capture group.
Before the `verify_tests_have_capture_groups` was added, running `bin/recog_verify xml/pop_banners.xml` produced:
```
WARN: 'Dovecot Secure POP Server' has no test cases
SUMMARY: Test completed with 32 successful, 1 warnings, and 0 failures
```
Now, with the `verify_tests_have_capture_groups` method called from the `verify_tests` method in `lib/recog/fingerprint.rb`, running `bin/recog_verify xml/pop_banners.xml` produces:
```
WARN: 'Qpopper with Sphera mods' is missing an example that …
```

verify that parameters from capture groups are tested by examples

---

.travis.yml
xml/ssh_banners.xml

This changeset adds missing fingerprints for Ubuntu, Debian, and FreeBSD versions.
The existing fingerprint coverage was missing quite a few versions.
`recog_verify` and `rspec`
New OS fingerprints for Ubuntu, Debian, and FreeBSD

Add Ubuntu, Debian, and FreeBSD fingerprints

---

xml/ssh_banners.xml

This PR
- Changes `os.cpe23` in `ssh_banners.xml` to use `{os.version}` instead of static strings where possible.
- Cleans up a few whitespace issues
Code consistency and to reduce copy/paste errors by removing static strings in favor of interpolation.
`rspec`

Whitespace cleanup/interpolation changes

---

xml/ssh_banners.xml

This PR adds extract tests for examples in `xml/ssh_banners.xml` with the goal of ensuring that we capture what we expect to capture.  This change leverages the new test added by @rhodgman-r7 in PR #244 for detecting when a fingerprint doesn't have any examples that validate a particular capture such as `service.version`. 
There were 3 or 4 banners with no examples.  I verified that I was unable to find any examples of these banners from recent Sonar studies.
Improved testing
`rspec`
`rake tests`
`bin/recog_verify xml/ssh_banners.xml`

Add extraction tests for ssh_banners

---

xml/smtp_banners.xml

Added a simple fingerprint for detecting OpenSMTPD servers.
RCE in OpenSMTPD (https://www.helpnetsecurity.com/2020/01/29/cve-2020-7247/) so having this in recog is faster/cleaner than regexp_like'ing a banner string
`bin/recog_verify xml/smtp_banners.xml | grep -i opensmtpd` (came up clean)
```
echo 'merovingian.attackbadger.com ESMTP OpenSMTPD' | bin/recog_match xml/smtp_banners.xml
MATCH: {"matched"=>"OpenSMPTD", "service.vendor"=>"OpenBSD", "service.family"=>"OpenSMTPD", "service.product"=>"OpenSMTPD", "os.cpe23"=>"cpe:/o:openbsd:openbsd:-", "service.cpe23"=>"cpe:/a:openbsd:opensmtpd:-", "host.name"=>"merovingian.attackbadger.com", "service.protocol"=>"smtp", "fingerprint_db"=>"smtp.banner", "data"=>"merovingian.attackbadger.com ESMTP OpenSMTPD"}
```
Tested a number of OpenSMTPD …

Added basic fingerprint for OpenSMTPD detection

---

xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/snmp_sysdescr.xml
xml/telnet_banners.xml
xml/x509_issuers.xml
xml/x509_subjects.xml

This PR rolls up a bunch of small changes, including consistency improvements around Terminal Servers (now Device Server) and IP Phones (now VoIP). New fingerprints were added for LANDesk, NetData, and Pulse Secure VPN. Small fixes were made to existing fingerprints (NetScaler). Cisco Tandberg and IP Phone fingerprints needed small tweaks for coverage.
Improve coverage and make existing coverage more consistent
Real-world scans, rspec, and recog_verify
- Consistency changes across fingerprints
- Small fingerprint updates
- New fingerprints

Small updates for consistency and coverage

---

xml/html_title.xml

This PR adds HTML TITLE fingerprints for Eagle Eye Networks  for their Cloud Video Surveillance System. ( https://www.een.com/product/cloud-vms-system-overview/ )
For example for `/`:
```
$ curl -sk  https://<redacted host>/ 
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Web Local Display Unauthorized</title>
<meta name="description" content="Bridge local login error">
<meta name="author" content="EagleEyeNetworks">
<link rel="icon" href="_images/favicon.ico" />
<link rel="stylesheet" href="_css/error_style.css">
<link rel="stylesheet" href="_css/bootstrap.min.css">
</head>
<body>
<div align="center" class="container">
<hr>
<p class="red">The user name and password that you have entered are incorrect.</p>
</div> 
</body>
</html>
```
Similarly for `index.html`:
``` …
```

add egale eye networks fingerprint

---

xml/apache_os.xml

This request includes an Apache HTTP banner fingerprint for newer versions of Red Hat Enterprise Linux.
Current Apache OS fingerprints do not adequately recognize the presented OS Vendor as Red Hat.
`echo 'Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips' | ./bin/recog_verify xml/apache_os.xml` has been used against the included example within the fingerprint.
The fingerprint has also been tested successfully as a custom Nexpose fingerprint within a relatively large production environment.  
Additional Signature

Include Red Hat Enterprise Linux HTTP Banner Fingerprint

---

bin/recog_standardize
identifiers/README.md
identifiers/os_architecture.txt
identifiers/os_device.txt
identifiers/os_family.txt
identifiers/os_product.txt
identifiers/service_family.txt
identifiers/service_product.txt
identifiers/software_class.txt
identifiers/software_family.txt
identifiers/software_product.txt
identifiers/vendor.txt
xml/architecture.xml
xml/ntp_banners.xml
xml/snmp_sysdescr.xml

This is a starter PR to demonstrate how the normalization towards known identifiers can work.
1) Fingerprints which asserted similar, but non-standard identifiers were fixed.
2) The identifier list was updated with the net-new entries from fingerprints.
Any feedback on this? This is a small example compared to what the vendors, os, or service updates will look like. The idea is that these changes are safe because they push more fingerprints to the identifiers already used by existing consumers. 
The goal is to standardize on as few unique identifiers as possible for all fingerprints.
- Non-breaking change to move existing fingerprints to known architecture constants.

Example: os_architecture.txt Normalization

---

xml/dns_versionbind.xml

This PR adds coverage for an additional DNS fingerprint of DNS running on Microsoft Windows 2008 SP2.  There are other misc DNS tweaks as well and some performance related changes.
The main thing I'm concerned about is the 'assert nothing' results that end up assigning a `service.protocol` value which is inherited from the XML database. 
```shell
$ echo '' | bin/recog_match xml/dns_versionbind.xml 
MATCH: {
"matched"=>"empty string -- assert nothing.", 
"service.protocol"=>"dns", 
"fingerprint_db"=>"dns.versionbind", 
"data"=>""}
```
I'm addressing this by setting `service.certainty` to `0.0.  It this logic makes sense we can apply it elsewhere when the same assert nothing style matches are used.
```shell
$ echo '' | bin/recog_match xml/dns_versionbind.xml 
MATCH: {
"matched"=>"empty …
```

DNS tweaks

---

xml/dns_versionbind.xml

This PR handles a spoofed DNS version bind response as well as adds coverage for Debian Buster.
The PR adds a fingerprint to assert nothing for a particular DNS `version.bind` response that claims to be Microsoft DNS server but isn't. The comment should explain the details. I tested using a quirk in how Microsoft handles `version.bind` queries.  They respond to lowercase version.bind queries but not uppercase queries. Pretty much everyone else handles the query in a case insensitive way. I sampled the servers reporting `Microsoft DNS 6.0.6100 (2AEF76E)` and was unable to find one that was actually a Microsoft DNS server.
Actual Microsoft DNS server response:
```shell
$ dig chaos txt VERSION.BIND  @96.94.199.217
; <<>> DiG 9.10.6 <<>> chaos txt VERSION.BIND @96.94.199.217
;; global …
```

DNS: Avoid spoofed Microsoft DNS Server, add Debian Buster

---

cpe-remap.yaml
update_cpes.py
xml/favicons.xml
xml/ftp_banners.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/snmp_sysdescr.xml

PR #272 re-raised an issue where `update_cpes.py` wasn't correctly mapping products which had a `/` in the name. The new PR correctly escapes the forward slash.
This:
```xml
<param pos="0" name="service.product" value="TCP/IP"/>
<param pos="0" name="service.vendor" value="Treck"/>`
```
should result in following.
```xml
<param pos="0" name="service.cpe23" value="cpe:/a:treck:tcp\/ip:{service.version}"/>
```
It was failing because it used `tcp/ip` instead of `tcp\/ip` which isn't a valid NIST issued CPE.  See: https://nvd.nist.gov/products/cpe/search/results?keyword=Treck&status=FINAL&orderBy=CPEURI&namingFormat=2.3
The PR also contains misc formatting fixes that were automatically handled by the scripts.
Correct CPE generating automation, few work arounds in `cpe-mapping.xml`
`rspec`
- …

CPE: Correct CPE generating automation

---

xml/ftp_banners.xml
xml/html_title.xml
xml/http_servers.xml
xml/imap_banners.xml
xml/pop_banners.xml
xml/snmp_sysdescr.xml
xml/ssh_banners.xml
xml/telnet_banners.xml

This PR improves coverage of Moxa products. It also contains various additions / improvements based on Project Sonar survey data.
Coverage improvements.
- Significant improvements in coverage, from a volume perspective, when testing against Project Sonar data.
- Coverage for multiple Moxa branded devices
- Performance tweaks for `xml/html_title.xml`
`rspec`,
built-in tests via `bin/recog_verify`
tests against data
- Coverage

Project Sonar: Moxa and misc

---

xml/snmp_sysdescr.xml

Changed wrong values of 2 fingerprints

Fix wrong values in snmp_sysdescr.xml

---

xml/snmp_sysdescr.xml

Added a SNMP fingerprint for SonicOS SonicWALL devices that do not include a hardware model in the snmp.banner.
The target that was being tested returnes the following snmp.banner:
```
SonicWALL SOHO (SonicOS Enhanced 5.9.1.4-4o)
```
Currently the fingerprinter that almost matches the above expects at least one digit after the hardware product, SOHO, and that digit or set of digits gets asserted as the hw.model.  
Because there's no hw.model in the fingerprint seen above, instead of making the hw.model optional (which would mean asserting a null hw.model for the above FP) we've added a second FP that doesn't expect a hw.model.
Rake tests run successfully. Deploying to nexpose now
```
9 scenarios (9 passed)
20 steps (20 passed) …
```

Added SonicOS FP

---

.snyk
update_cpes.py
xml/favicons.xml
xml/html_title.xml
xml/http_servers.xml
xml/smtp_banners.xml
xml/smtp_help.xml
xml/snmp_sysdescr.xml
xml/telnet_banners.xml
xml/x509_issuers.xml
xml/x509_subjects.xml

This PR changes `update_cpes.py` so that it uses `yaml.safe_load()` instead of `yaml.load()`. This should reduce the risk when loading YAML.  I've also run it against our fingerprint databases using the latest data from NIST.
I've also added a `.snyk` file in order to suppress the Synk warning on PyYAML. We don't currently use a vulnerable code path, Snyk doesn't check to see if you are using the vulnerable code path, and there is no full library level fix for this other than to use `safe_load()` (which this PR does) or the `SafeLoader` loader.
https://app.snyk.io/vuln/SNYK-PYTHON-PYYAML-590151
Risk reduction
`rspec`, Github PR hooks
- Breaking change (fix or feature that …

CPE: use safe_load, update CPEs

---

xml/dns_versionbind.xml

The attached PR extracts build information for Microsoft DNS Server into `service.version.version`. This field use is consistent with build information from other DNS services. I'd added extraction tests for the existing examples.
Note, this isn't the *TRUE* build information but does contain the build information.  For example on my test Windows 2008 R2 server the version string on the binary is `6.1.7601.24437`.  
The string value returned in the version bind response is `Microsoft DNS 6.1.7601 (1DB15F75)`.
`1DB1` = `7601`
`5F75`  = `24437`.
Recog cannot return the exact build, `24437`, without manipulating a substring of `1DB15F75`. We don't currently support that in Recog proper (Ruby), or, as far as I know, in the Go or Java versions.
Provide the ability to determine the build level …

DNS: Extract Microsoft DNS build

---

xml/dns_versionbind.xml

A fingerprint pattern has been added for Microsoft DNS versions on Windows 2003. We have added Windows 2003 as one fingerprint as Windows 2003 and Windows 2003 R2 use the same kernel version.
This change is being made to allow recog to support Microsoft DNS versions in the format of "5.2.3790.x" for Windows 2003.
The changes were tested by running `bin/recog_verify xml/dns_versionbind.xml`.
**Test result:**  
`14:22 $ bin/recog_verify xml/dns_versionbind.xml`
`SUMMARY: Test completed with 145 successful, 0 warnings, and 0 failures`

DNS fingerprint for Windows 2003

---

bin/recog_standardize

This PR addresses what I believe to a bug in `bin/recog_standardize` in which a string index is compared to `-1` instead of `nil`. Since `-1` shouldn't be a valid response to this check all entries were skipped.
I noticed this when working on PR #301 and not seeing some of the changes I made. I then added a random vendor name and `recog_standardize` didn't report it.
**NOTE**: In this PR I have not included the changes to the files in `identifiers/` since I need some of the changes in PR #301 to land first. When the issue is addressed I'll open a PR to clean up.
You can see the results either of the following commands before and after the changes in this PR.
CC @hdm 
```
ruby bin/recog_standardize xml/http_servers.xml
for db in xml/*.xml; do ruby bin/recog_standardize $db; done
```
```
$ …
```

recog_standardize: adjust logic

---

xml/http_servers.xml

Simply adds a low certainty to the IIS 10 fingerprint as it has a lot of null fields and without the certainty it defaults to 0.8 which actually ends up trumping fingerprints with more information.
I have ran a scan against an IIS 10 host before and after the change and noted this fingerprint no longer trumps others which have more information.

Add low certainty to IIS 10 fingerprint to prevent trumping better system fingerprints

---

cpe-remap.yaml
xml/smb_native_lm.xml
xml/smb_native_os.xml

The PR adds fingerprints to `smb_native_os` and `smb_native_lm` based on data from Project Sonar scans.
Highlights:
- Add Hyper-V coverage for Windows 2019, 2016, 2012 R2, 2012, and 2008 R2
- Improved Windows Storage Server coverage
- Assert nothing for `Windows 6.1` as this has typically only been seen with Samba
- Multiple fingerprints for IBM midrange devices
- Misc other changes
`rspec`
Fingerprint improvements

SMB fingerprint improvements

---

.github/workflows/ci.yml
xml/smb_native_os.xml

This PR adds a Github Actions CI workflow configuration to run tests automatically. I have configured the same Ruby versions used in the existing travis-ci config and added newer ones as well. Note: the jruby version used on travis-ci is not available for this GHA workflow, so a newer version was selected along with latest released jruby.
Additionally an invalid example was fixed to get tests to pass.
Note that the new workflow will begin running immediately when this PR is merged.
travis-ci has migrated open source repos from their .org platform to their .com platform, which now includes a limited number of worker credits. Currently, the R7 org has exhausted available worker credits and the UI doesn't indicate when they will be replenished. As such, tests on this repo are not currently …

Add Github Actions CI workflow

---

xml/favicons.xml
xml/html_title.xml

Added SolarWinds Orion fingerprints in html_title.xml and favicons.xml

Added SolarWinds Orion fingerprints

---

xml/html_title.xml

Adds a fingerprint for VMware vCenter. 
This is sort of experimental. The VMware vCenter page content looks like this:
```
<script type="text/javascript">document.write("<title>" + ID_VC_Welcome + "</title>");</script>
```
At least Shodan and Censys both grab the page title as `" + ID_VC_Welcome + "`.  However, it's obviously meant to be interpreted, as it's javascript (likely because of internationalization -- if you view what the page title ends up being after this is interpreted, it is "Welcome to VMware vSphere").
If we're OK with HTML title tag matching to be defined as simply "whatever is in the static text representation of two enclosing title tags" I think this fingerprint is valid. If we think it that title tag retrieval is defined by some other means (interpreted, etc.) then we …

Add a vCenter fingerprint based on HTML title

---

xml/html_title.xml
xml/http_cookies.xml

The Sage X3 web application server (Syracuse) can be identified by a cookie in the format of "syracuse.sid.<digits>", making it a pretty simple signature.
The Sage X3 web interface uses a predictable cookie to identify it. This is a heavily deployed ERP product. Some product info:
* https://www.sage.com/en-us/
* https://en.wikipedia.org/wiki/Sage_X3
Match test:
```
~/src/recog $ printf 'syracuse.sid.8124=8b102bf7-327c-4962-9279-550e72afcaa9; path=/; HttpOnly\n' | ./bin/recog_match xml/http_cookies.xml -
MATCH: {"matched"=>"Sage X3 Syracuse Web Server", "cookie"=>nil, "service.vendor"=>"Sage", "service.family"=>"Sage X3 Syracuse Web Server", "service.product"=>"Sage X3 Syracuse Web Server", "service.protocol"=>"http", "fingerprint_db"=>"http_header.cookie", …
```

Added Sage X3 Syracuse fingerprints

---

cpe-remap.yaml
identifiers/os_product.txt
identifiers/service_family.txt
identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/ldap_searchresult.xml
xml/ntp_banners.xml
xml/sip_banners.xml
xml/sip_user_agents.xml
xml/tls_jarm.xml

This PR includes:
- General fixup after landing PRs
- CPE updates with using today's NIST CPE database
Quality / consistency.
`rspec`

CPE / example cleanup

---

xml/http_servers.xml

This PR corrects a regex used for IPv4 addresses used in `http_servers.xml`.  The regex failed to escape a `.` and could DoS the parser when processing very long numeric sequences.
The PR correctly escapes the period and limits the number of repeating digits allowed before the match fails.
This issue was highlighted in a PR to `recog-java` here: https://github.com/rapid7/recog-java/pull/7
Bug fix, performance improvement
`rspec` with built in `example` tests.  I have also tested the regex with Go and Rust online regex testers. Both of these languages use the RE2 engine by default.

http_servers: fix incorrect IP regex

---

cpe-remap.yaml
identifiers/os_device.txt
identifiers/os_family.txt
identifiers/os_product.txt
identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/http_servers.xml
xml/snmp_sysdescr.xml
xml/x509_subjects.xml

This PR tweaks the fields for Palo Alto so as to return better data and/or improve the ability to generate CPEs.
I would have preferred to change `PANOS` to `PAN-OS` for the `os.product` but I wasn't sure what this would break downstream.
I also reset and regenerated the contents of the `identifiers/` directory.

Palo Alto Tweaks

---

cpe-remap.yaml
identifiers/hw_family.txt
identifiers/hw_product.txt
identifiers/os_product.txt
identifiers/service_product.txt
update_cpes.py
xml/favicons.xml
xml/ftp_banners.xml
xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/ntp_banners.xml
xml/smtp_banners.xml
xml/smtp_expn.xml
xml/smtp_vrfy.xml
xml/snmp_sysdescr.xml
xml/ssh_banners.xml
xml/x509_issuers.xml
xml/x509_subjects.xml

This PR addresses an issue brought up by @p0lr in Issue #343. In that issue @p0lr points out that we're using deprecated CPE values and that the NIST database that we're already using indicates that the values are deprecated.
I've adjusted the matching logic in `update_cpes.py` so that these deprecated CPEs aren't added when we build our list of NIST issued CPEs.
I've also restructured `cpe-remap.yaml` so that we remap values are specific to a CPE type (`a`, `o`, `h`). This will allow us to remap certain older records that use the same `.product` value but for which the CPE would be different between `service.product` and `os.product`.
For example in the fingerprint below we couldn't have created a remap for `ILOM` under `oracle` because it would have then generated (or tried to generate) …

CPE: stop using deprecated CPEs, split the remap YAML into sections

---

cpe-remap.yaml
identifiers/hw_product.txt
xml/mdns_device-info_txt.xml

Add AppleTV 4K second generation to `xml/mdns_device-info_txt.xml`. Values observed in PCAPs.
Reference: https://www.theiphonewiki.com/wiki/J305AP
I've also added some CPE remaps for recent Apple hardware.

MDNS: Add AppleTV 4K second gen

---

cpe-remap.yaml
identifiers/fields.txt
identifiers/os_product.txt
lib/recog/nizer.rb
xml/ftp_banners.xml
xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/telnet_banners.xml
xml/x509_subjects.xml

This PR implements the change discussed in Issue #364. 
The changes:
- changes `host.id` to `hw.serial_number` where the value is a hardware serial number
- changes `host.id` to `host.name` where the value references a host name
- in each case where there is a vendor specific serial number field such as `cisco.serial_number` that value is duplicated in `hw.serial_number` and a test added for it.
The intent is to add clarity to the data that is captured. The field `host.id` was unclear and was being used to capture hostnames as well as serial numbers.
`rspec`, fingerprint example captures.
- Field rename

Field migration: host.id -> hw.serial_number

---

xml/html_title.xml
xml/http_servers.xml
xml/sip_banners.xml
xml/smtp_banners.xml
xml/telnet_banners.xml
xml/x509_issuers.xml

The intent of this PR is to improve cross language compatibility for the regex patterns used. 
The changes:
- Moves inline flags such as `(?i)` and `(?m)` to the beginning of the regex.  In Python these flags have global meaning and use of them anywhere other than the start of the pattern is deprecated. This does not change the function of these flags in current patterns for other languages.
- Replaces the use of POSIX character class indicators (`[[:alnum:]]`, `[[:digit:]`, and `[[:space:]`) with either the short backslash version (`\d`, `\s`) or a character range (`a-zA-Z0-9`).  The reason for this is that certain languages (Java, Python, Javascript) don't support the use of POSIX character classes.
`rspec`, 3rd party regex testors.
Fingerprint construction

Regex cross-language compatibility

---

xml/apache_os.xml
xml/ftp_banners.xml
xml/html_title.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/imap_banners.xml
xml/nntp_banners.xml
xml/ntp_banners.xml
xml/operating_system.xml
xml/pop_banners.xml
xml/sip_banners.xml
xml/smtp_banners.xml
xml/snmp_sysdescr.xml
xml/ssh_banners.xml
xml/telnet_banners.xml

TL:DR - Fixed an unlikely DoS condition in a pattern in `xml/ssh_banners.xml` and improved performance of certain patterns.  Metrics included here.  This PR doesn't address all of the slower patterns but does get the worst of them.
In a PR ( https://github.com/rapid7/recog-java/pull/7 ) for `recog-java` @hudclark provided some data ( https://github.com/rapid7/recog-java/pull/7#issuecomment-829254286 ) that would cause one of our regexes to hang indefinitely.  That specific problem has already been fixed https://github.com/rapid7/recog/pull/353.
Since `recog` is generally used to process data from untrustworthy sources I wanted to make sure that this specific data and certain other patterns wouldn't cause indefinite hangs or otherwise have unacceptable performance characteristics when …

DoS fix / regex performance tuning

---

xml/dns_versionbind.xml
xml/ftp_banners.xml
xml/html_title.xml
xml/http_servers.xml
xml/sip_user_agents.xml
xml/smb_native_os.xml
xml/telnet_banners.xml
xml/x509_issuers.xml

This PR explicitly sets the certainty levels for certain `Assert Nothing` style fingerprint matches.  The intent is to convey that all other matches to a banner or endpoint should be given priority over these specific matches. For example, a http_server match may be too generic to have value but the x509 issuer may also match and we want that second one to win always.
`rspec`

Add explicit certainty for Assert Nothings

---

CONTRIBUTING.md
bin/recog_standardize
tools/dev/hooks/pre-commit

Introduces a git pre-commit hook to run `bin/recog_standardize` on any staged XML fingerprint files. This will help contributors verify that each fingerprint asserts known identifiers. These changes required enhancement of `bin/recog_standardize` to return an exit code in order to support scripting.
Help contributors catch concerns before changes are committed and pull requests are opened. Save everyone a little time and help get contributions merged quicker!
New field names and new field values were added to xml fingerprints, then attempted to commit the changes to trigger the pre-commit hook script.

Add recog_standardize pre-commit hook

---

xml/ftp_banners.xml
xml/html_title.xml
xml/http_wwwauth.xml
xml/operating_system.xml
xml/smtp_banners.xml
xml/snmp_sysdescr.xml

This PR changes the maximum repetition size so as to be compatible with Go's regex requirements.
The character class repetition limits were added to some fingerprints in PR #368 with the goal of reducing the impact that matches of unbounded sizes could have on performance.  The value of `1024` was somewhat arbitrarily selected as a value that was large enough to allow for all expected values while still having some reasonable limit.  `1000` will serve just as well and is supported by Go.
Reference: https://pkg.go.dev/regexp/syntax
> Implementation restriction: The counting forms x{n,m}, x{n,}, and x{n} reject forms that create a minimum or maximum repetition count above 1000. Unlimited repetitions are not subject to this restriction.
We have plans to implement better cross-language …

Issue #370: Go regex breakage

---

features/verify.feature
lib/recog/fingerprint.rb

Removes the word "messsage" from a message string since it appears to be there by mistake.
To fix an error.
Ran `./bin/recog_verify` and verified the message was output correctly.

Remove unnecessary word from verify message

---

xml/telnet_banners.xml

Small `xml/telnet_banners.xml` pattern modifications to fix issues with `recog-java` compatibility.
Resolve `recog-java` fingerprint issues introduced when adding support for base64 encoded examples in rapid7/recog-java#15.
```
xml/telnet_banners.xml: FAIL: 'HP Printer - Jet Direct' failed to match "HP JetDirect
<snip>
" with '^(?:\r|\n)*HP JetDirect(?:\r|\n)+$'
xml/telnet_banners.xml: FAIL: 'HP Printer - Jet Direct' failed to match "HP JetDirect
<snip>
" with '^(?:\r|\n)*HP JetDirect(?:\r|\n)+$'
xml/telnet_banners.xml: FAIL: 'Windows 2000' failed to match "Microsoft (R) Windows NT (TM) Version 4.00 (Build 1381)
<snip>
login: " with '^Telnet Server Build (5.*)'
xml/telnet_banners.xml: WARN: 'Arescom System' is missing an example that checks for parameter 'hw.model' which is derived from a …
```

Modify telnet patterns to fix recog-java compatibility

---

xml/telnet_banners.xml

Small `xml/telnet_banners.xml` pattern modifications to fix issues with `recog-java` compatibility.
Resolve `recog-java` fingerprint issues introduced with new fingerprints from #382.
```
$ mvn --projects recog-verify exec:java -Dexec.mainClass="com.rapid7.recog.verify.RecogVerifier" -Dexec.args="--no-warnings xml/telnet_banners.xml"
...
xml/telnet_banners.xml: FAIL: 'Lantronix device server - w/o Serial' failed to match "*** Lantronix UDS1100-IAP Device Server ***
<snip>
" with '(?m)\*\*\* Lantronix ([\S+ ]+) Device Server .{0,1000}MAC address ([a-fA-F0-9]{12}).{0,1000}Software version V(\S+)'
xml/telnet_banners.xml: FAIL: 'Lantronix device server - w/ Serial' failed to match "*** Lantronix Universal Device Server ***
<snip>
" with '(?m)\*\*\* Lantronix Universal Device Server …
```

Modify telnet patterns to fix recog-java compatibility (2)

---

identifiers/hw_device.txt
xml/http_wwwauth.xml
xml/telnet_banners.xml
xml/x509_subjects.xml

Corrects `hw.device` capitalization for "Web Cam".
All `hw.device` values should be formatted using start case.
* `rake tests`
* `./bin/recog_verify --no-warnings xml/*.xml`

Correct hw.device capitalization for Web Cam

---

Rakefile
features/verify.feature
lib/recog/fingerprint.rb
lib/recog/verifier.rb
lib/recog/verify_reporter.rb

Just a simple patch to produce line numbers in parsed fingerprints.
Need this to tell which fingerprints are which when diagnosing and fixing problems reported by `recog_verify`
Ran `recog_verify`
Ran `bundle exec rake tests`

Resolve #389: Add line numbers to recog_verify output

---

.github/workflows/ci.yml

Increments the lower JRuby version to `9.2.20.1` to match the Ruby 2.5 lower version.
> JRuby 9.2.20.1 is our point release of our Ruby 2.5.x support.
Keeping testing consistent and resolving a test issue on #393.
Changes will be tested via the GitHub Action.

Increment lower JRuby version to 9.2.20.1

---

xml/tls_jarm.xml

Add two jarm c2 fingerprints, one for msf, one for cobalt strike
TLS stacks used by C2 are being modernized, so recog should keep up with this.
Locally, and confirmed by https://thedfirreport.com/2022/01/24/cobalt-strike-a-defenders-guide-part-2/ and https://github.com/cedowens/C2-JARM

Add two jarm c2 fingerprints, one for msf, one for cobalt strike

---

xml/tls_jarm.xml

Add a jarm fingerprint for HP Printers
More ways to detect HP Printers, yay!
Tested on my LAN, as well as on https://www.shodan.io/search?query=ssl.jarm%3A16d16d16d14d16d00016d16d16d16da6fda484e06f95db4f56339284c90672

Add a jarm fingerprint for HP Printers

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Adds two fingerprints for MITRE's [CALDERA](https://github.com/mitre/caldera) C2 framework. Note, while the comment at the top of `xml/favicons.xml` mentions `favicon.ico` explicitly the MD5 for CALDERA's favicon is from a PNG.
```
<link rel="shortcut icon" type="image/png" href="/gui/img/favicon.png"/>
``` 
More C2 fingerprints for recog.
* CALDERA installed and run following the directions for [Docker Deployment](https://caldera.readthedocs.io/en/latest/Installing-CALDERA.html#docker-deployment)
* `rake tests`

Add CALDERA C2 fingerprints

---

xml/tls_jarm.xml

Adds three more Metasploit JARM fingerprints.
Updates Metasploit JARM fingerprints to reflect different `SSLVersion` settings.
* metasploit-framework version:
```
Framework: 6.1.25-dev-f509e0955e
Console  : 6.1.25-dev-f509e0955e
```
* Settings information:
```
msf6 exploit(multi/handler) > advanced
...
Payload advanced options (multi/meterpreter/reverse_https):
...
HandlerSSLCert                                            no        Path to a SSL certificate in unified PEM format
, ignored for HTTP transports
...
SSLVersion                   Auto                         yes       Specify the version of SSL/TLS to be used (Auto
, TLS and SSL23 are auto-negotiate) (Accepted:
Auto, TLS, SSL23, SSL3, TLS1, TLS1.1, TLS1.2)
```
* Test SSLVersion TLS1:
```
msf6 > use exploit/multi/handler
[*] …
```

Add more Metasploit JARM fingerprints

---

features/verify.feature
lib/recog/fingerprint.rb

A simple change to eliminate spurious warnings produced by Ruby `recog_verify` when no examples are present. In other words, instead of emitting these warnings:
```
xml/smtp_help.xml:49: WARN: 'IBM VM' has no test cases
xml/smtp_help.xml:49: WARN: 'IBM VM' is missing an example that checks for parameter 'host.name' which is derived from a capture group
```
The code will now emit:
```
xml/smtp_help.xml:49: WARN: 'IBM VM' has no test cases
```
For this fingerprint:
```
<fingerprint pattern="^214[ -]([^ ]+) is running the IBM VM operating system$">
<description>IBM VM</description>
<param pos="0" name="service.vendor" value="IBM"/>
<param pos="0" name="service.family" value="VM"/>
<param pos="0" name="service.product" value="VM"/>
<param pos="1" name="host.name"/>
</fingerprint>
```
It will …

Eliminate warnings when no examples are present in fingerprints

---

xml/dhcp_vendor_class.xml
xml/dns_versionbind.xml
xml/ftp_banners.xml
xml/h323_callresp.xml
xml/hp_pjl_id.xml
xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/imap_banners.xml
xml/nntp_banners.xml
xml/ntp_banners.xml
xml/operating_system.xml
xml/pop_banners.xml
xml/sip_banners.xml
xml/sip_user_agents.xml
xml/smb_native_lm.xml
xml/smb_native_os.xml
xml/smtp_banners.xml
xml/smtp_help.xml
xml/snmp_sysdescr.xml
xml/snmp_sysobjid.xml
xml/ssh_banners.xml
xml/x509_subjects.xml

Adds missing example attributes to `<example>` elements in recog fingerprint XML files, greatly reducing recog_verify warnings.
This is only round 1. Subsequent rounds will target some hand modifications to target fingerprints missing examples altogether. Additionally, there is one warning that is not fixed with this patch due to it being an edge case: The fingerprint regex conditionally matches a version, but the only example does not supply one. That will be fixed by hand as well in a subsequent PR.
The script that was used to make these changes is here:
https://gist.github.com/dabdine/6c641407e805ab33530ec67459a94c3a
Clean up warnings so that more strict enforcement of quality can eventually be turned on.
Ran recog_verify

Scripted update to add missing example attributes

---

xml/http_servers.xml
xml/operating_system.xml
xml/sip_user_agents.xml
xml/smtp_banners.xml

Fixes these additional warnings that #400 did not address due to the examples missing content that could be parsed by the regular expression:
```
xml/http_servers.xml:1225: WARN: 'Sun Java System Application Server (formerly iPlanet Application Server, Sun ONE Application Server)' is missing an example that checks for parameter 'service.version' which is derived from a capture group
xml/operating_system.xml:59: WARN: 'Windows 2000' is missing an example that checks for parameter 'os.version' which is derived from a capture group
xml/operating_system.xml:228: WARN: 'Gentoo Linux' is missing an example that checks for parameter 'os.version' which is derived from a capture group
xml/operating_system.xml:663: WARN: 'IBM OSes' is missing an example that checks for parameter 'os.version' which …
```

Fix additional warnings due to untested attributes

---

xml/architecture.xml
xml/ftp_banners.xml
xml/ssh_banners.xml

Fixes fingerprint examples & regular expression issues in `ftp_banners.xml`, `architecture.xml`, and `ssh_banners.xml`. These files no longer yield any warnings whatsoever.
Eliminate more warnings & fix bad regular expressions in some fingerprints.

Fix examples in architecture.xml, ftp_banners.xml, and ssh_banners.xml

---

xml/apache_os.xml

Addresses all warnings in `apache_os.xml` using real data from Censys.
Eliminate warnings due to missing examples.

Fix all examples in apache_os.xml

---

features/data/tests_with_failures.xml
features/verify.feature
lib/recog/fingerprint.rb
spec/lib/recog/fingerprint_spec.rb

Enhances `recog_verify` to report an untested parameter as a failure instead of a warning.
Ensure all fingerprints have examples that fully verify all capture group parameters.
* `rake tests`

Enhance recog verify to report an untested parameter as a failure

---

xml/http_servers.xml

Fixes a greedy `service.version` capture group for EmWeb variants.
Fixes incorrect matches where the EmWeb variant server header appears in a large string of HTTP server headers.
* `rake tests`
* `echo "Server Server Server Virata-EmWeb/R6_2_1 Server Server Server" | ./bin/recog_match xml/http_servers.xml`

Fix greedy service.version capture group for EmWeb variants

---

identifiers/service_family.txt
identifiers/service_product.txt
identifiers/vendor.txt
xml/http_servers.xml

Adds a fingerprint for teamspeak. Over 20K of these on the internet, [according to Censys](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=same_service%28not+services.software.product%3A*+and+services.service_name%3A+HTTP+and+services.http.response.headers.server%3ATeamSpeak*%29).
```
echo -n "TeamSpeak Server 3.13.6" | bin/recog_match xml/http_servers.xml | cut -c 8- | sed 's/=>/:/g' | jq .
{
"matched": "TeamSpeak HTTP server",
"service.vendor": "TeamSpeak",
"service.product": "TeamSpeak",
"service.family": "TeamSpeak",
"service.version": "3.13.6",
"service.cpe23": "cpe:/a:teamspeak:teamspeak:3.13.6",
"service.protocol": "http",
"fingerprint_db": "http_header.server",
"data": "TeamSpeak Server 3.13.6"
}
```
- New …

Add teamspeak http server fingerprint

---

identifiers/service_family.txt
identifiers/service_product.txt
identifiers/vendor.txt
xml/http_servers.xml

Adds a fingerprint for WebSocket++. There are over 72K of these on the internet, [according to Censys](https://search.censys.io/search?resource=hosts&sort=RELEVANCE&per_page=25&virtual_hosts=EXCLUDE&q=same_service%28not+services.software.product%3A*+and+services.service_name%3A+HTTP+and+services.http.response.headers.server%3AWebSocket%2B%2B*%29).
The server git repository is on GH:
https://github.com/zaphoyd/websocketpp
Adds a fingerprint

Add a WebSocket++ fingerprint

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_cookies.xml

Adds 3 [phpMyAdmin](https://www.phpmyadmin.net/) fingerprints.
Fingerprint more services.
* `rake tests`

Add phpMyAdmin fingerprints

---

cpe-remap.yaml

A follow-up to #414 to prevent `update_cpes.py` from removing the `service.cpe23` param by adding a Zaphoyd Studios WebSocket++ remap entry to `cpe-remap.yaml`
The motivation is to maintain the correct `service.cpe23` value for Zaphoyd Studios WebSocket++. I considered updating fingerprint's `service.vendor` and `service.product`, however, those values seem more correct and complete.
* `python update_cpes.py xml/http_servers.xml official-cpe-dictionary_v2.3.xml cpe-remap.yaml`

Add Zaphoyd Studios WebSocket++ remap entry

---

identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [Apache Spark](https://spark.apache.org/) fingerprints. Also, adds missing `os.cpe23` param in `xml/favicons.xml` for LG webOS.
* `rake tests`

Add Apache Spark fingerprints

---

bin/recog_verify
lib/recog/fingerprint.rb
lib/recog/fingerprint_parse_error.rb
spec/data/external_example_fingerprint.xml
spec/data/external_example_fingerprint/hp_printer_ex_01.txt
spec/data/external_example_fingerprint/hp_printer_ex_02.txt
spec/data/external_example_illegal_path_fingerprint.xml
spec/lib/recog/db_spec.rb

Fixes path traversal issue with example `_filename` attribute. Thanks to @dabdine for bringing attention to the issue! In addition, this enhances `bin/recog_verify` to be more resilient if an exception occurs while processing more than one fingerprint file.
```
<example _filename="../../../illegal/path"/>
```
Ensure recog doesn't access files and directories that are out of scope.
* `rake tests`
* `./bin/recog_verify` with test fingerprints copied into the XML directory
```
<?xml version='1.0' encoding='UTF-8'?>
<fingerprints matches="test-path-traversal" protocol="test" database_type="test" preference="0.90">
<fingerprint pattern="^dne$">
<description>path traversal test</description>
<example _filename="../path-traversal"></example>
</fingerprint>
</fingerprints>
```
```
<?xml …
```

Fix path traversal issue with example filename

---

identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

* Adds pfSense and Netgate pfSense Plus firewall fingerprints. Corrects `xml/favicons.xml` pfSense fingerprint since we are unable to assert hardware parameters based on the available data.
* `rake tests`

Add pfSense and Netgate pfSense Plus firewall fingerprints

---

cpe-remap.yaml
update_cpes.py
xml/favicons.xml
xml/html_title.xml
xml/http_servers.xml

This PR updates the output of the `update_cpes.py` script so as to indicate when it failed to generate a CPE due to that CPE being deprecated in the NIST official database.
```
ERROR:root:Product nginx from vendor nginx invalid for CPE a and no mapping.  This combination is DEPRECATED by a:f5:nginx at 2021-11-01T16:02:37.240Z
ERROR:root:Product nginx from vendor nginx invalid for CPE a and no mapping.  This combination is DEPRECATED by a:f5:nginx at 2021-11-01T16:02:37.240Z
ERROR:root:Product nginx from vendor nginx invalid for CPE a and no mapping.  This combination is DEPRECATED by a:f5:nginx at 2021-11-01T16:02:37.240Z
ERROR:root:Product mds_9000 from vendor cisco invalid for CPE o and no mapping.  This combination is DEPRECATED by o:cisco:mds_9000_san-os at 2010-12-28T17:36:45.943Z …
```

update_cpes.py: add deprecation info to output

---

xml/operating_system.xml
xml/pop_banners.xml

Fixes regex capture issues pointed out in #400.
Fix regex issues discovered after adding missing example capture group attributes.
* Verified "Windows 10 Mobile" `os.edition` was not incorrectly captured
```
$ echo "Windows 10 Mobile Edition" | ./bin/recog_match xml/operating_system.xml
MATCH: {"matched"=>"Windows 10 Mobile", "os.vendor"=>"Microsoft", "os.family"=>"Windows", "os.product"=>"Windows 10 Mobile", "os.edition"=>nil, "os.device"=>"Mobile", "os.cpe23"=>"cpe:/o:microsoft:windows_10_mobile:-", "service.protocol"=>"", "fingerprint_db"=>"operating_system.name", "data"=>"Windows 10 Mobile Edition"}
$ echo "Windows 10 Mobile" | ./bin/recog_match xml/operating_system.xml
MATCH: {"matched"=>"Windows 10 Mobile", "os.vendor"=>"Microsoft", "os.family"=>"Windows", "os.product"=>"Windows 10 …
```

Fix regex capture issues pointed out in #400

---

identifiers/service_product.txt
xml/http_servers.xml

Enhances two Oracle HTTP server fingerprints and adds three new HTTP server fingerprints.
There are notable changes to the "Oracle Application Server" fingerprint in `xml/http_servers.xml`
* `service.vendor` changed from "Apache" to "Oracle"
* `service.product` changed from "HTTPD" to "Application Server"
* `apache.variant.version` renamed to `service.version` since the captured value is not an apache version
* `apache.info` already captured more than apache information, but it will capture even more with these changes. The parameter should likely be renamed to `service.info` or removed.
Fingerprint more services.
* `rake tests`
* `./bin/recog_verify xml/http_servers.xml`

Oracle HTTP server enhancements

---

cpe-remap.yaml
identifiers/os_product.txt
xml/apache_os.xml
xml/dns_versionbind.xml
xml/html_title.xml
xml/http_servers.xml
xml/snmp_sysdescr.xml
xml/x11_banners.xml

Updates `os.vendor` and `os.product` parameter values on fingerprints for the recently deprecated `o:redhat:fedora_core` CPE. The OS vendor remap was added to improve fingerprint readability ("Fedora Project" rather than "FedoraProject").
From official-cpe-dictionary_v2.3.xml:
```
<cpe-item name="cpe:/o:redhat:fedora_core:-" deprecated="true" deprecation_date="2022-02-03T17:19:40.583Z">
```
Updated CPE values is good for consumers.
* `rake tests`

Update recently deprecated o:redhat:fedora_core CPE

---

identifiers/os_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/x509_issuers.xml

Adds fingerprints for [Tomato](http://www.polarcloud.com/tomato), [TomatoUSB](http://tomatousb.org/) (including [mods](http://tomatousb.org/mods) or "community developed branches of TomatoUSB"), and [FreshTomato](https://freshtomato.org/) router firmware. Note, the favicon file is the same across all of the firmware versions.
* `rake tests`

Adds various Tomato router firmware fingerprints

---

cpe-remap.yaml
identifiers/hw_device.txt
identifiers/hw_product.txt
identifiers/os_device.txt
identifiers/os_product.txt
identifiers/service_product.txt
identifiers/vendor.txt
xml/html_title.xml
xml/http_servers.xml
xml/sip_banners.xml
xml/sip_user_agents.xml
xml/telnet_banners.xml

Add fingerprints for various Eltex branded network equipment.
Vendor website: https://eltex-co.com/catalog/
All existing CPE currently issued by NIST.
```
h:eltex-co:ntp-2
h:eltex-co:ntp-rg-1402g
h:eltex:esp-200
o:eltex-co:ntp-2_firmware
o:eltex-co:ntp-rg-1402g_firmware
o:eltex:esp-200_firmware
```
`sofia-sip` reference: https://github.com/freeswitch/sofia-sip
Verification of TAU firmware numbering scheme: https://eltex-co.com/catalog/tau-16-ip-en.php
Verification of sofia-sip version numbering scheme: https://github.com/freeswitch/sofia-sip/releases
`rspec`
Fingerprint additions

Add Eltex fingerprints

---

xml/http_servers.xml
xml/sip_user_agents.xml
xml/telnet_banners.xml

Follow-up to enhance Eltex TAU-* fingerprints introduced in #434.
* Add `os.product` for Eltex TAU HTTP server fingerprint
* Constrain model match to avoid matching non-existing models such as `TAU-8.I`, `TAU-8.P`, `TAU-8.100`
* Expand regex with serial number and sofia version allow matching models that include a letter in the model number such as `TAU-32M.IP`
* Expand serial number regex to include alpha characters since I located devices that included a single letter following the format `VI3A######` and `VI4D######`.
Improved Eltex coverage.
* `rake tests`
* ` ./bin/recog_verify`

Enhance Eltex TAU model VoIP gateway fingerprints

---

identifiers/device.txt
identifiers/hw_product.txt
identifiers/os_product.txt
identifiers/vendor.txt
xml/telnet_banners.xml

Adds a telnet banner fingerprint for the Baxter SIGMA Spectrum Infusion System. The Wireless Battery Module is a separate device from the infusion system and has its own firmware (`SW: 20 D29` in the example). The fingerprint should be revisited to extract the value when there is a more clear path for handling sub-devices.
* `rake tests`

Add Baxter SIGMA Spectrum Infusion System fingerprint

---

xml/favicons.xml
xml/html_title.xml

Adds a WatchGuard Fireware XTM web interface favicon fingerprint and enhances the existing HTML title fingerprint with `service.device`, `os.device`, and `service.component.*`.
* `./bin/recog_verify xml/favicons.xml`
* `./bin/recog_verify xml/html_title.xml`
* `rake tests`

Add WatchGuard Fireware XTM favicon fingerprint

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_servers.xml

Adds fingerprints for WSO2 Carbon, API Manager, Identity Server and Enterprise Integrator.
The `service.component.product` param for the various products is set to "Carbon" as they all appear to be built on top of it. From [WSO2 Carbon Documentation (4.4.11)](https://docs.wso2.com/display/Carbon4411/WSO2+Carbon+Documentation):
> WSO2 Carbon is the award-winning, light-weight, service-oriented platform that includes all WSO2 products.
* `rake tests`

Add WSO2 product fingerprints

---

xml/http_servers.xml

Corrects the port number portion of an "assert nothing" HTTP server regex.
Correct regex.
* Added example with 5 digit port number
* `./bin/recog_verify xml/http_servers.xml`

Fix port number portion of an assert nothing HTTP server regex

---

identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds fingerprints for more Jupyter products (Jupyter Server, JupyterHub, BinderHub) and removes the product from the existing favicon since it is used on multiple products.
* `rake tests`
* `./bin/recog_verify xml/favicons.xml`
* `./bin/recog_verify xml/html_title.xml`

Add more Jupyter product fingerprints

---

identifiers/service_product.txt
xml/x509_subjects.xml

Adds [Duo Device Health](https://duo.com/docs/device-health) and [Duo Mac Certifier](https://duo.com/docs/trusted-endpoints-macos-certifier) x509 fingerprints. This is being added in the go string format so that it isn't lost in my backlog. #360 needs to be addressed in the near future.
* `bundle exec ./bin/recog_verify xml/x509_subjects.xml`
* `rake tests`

Add Duo Device Health and Mac Certifier x509 fingerprints

---

Rakefile
bin/recog_match
features/match.feature

Adds `recog_match` support for JSON output. These changes require recog gem enhancements from rapid7/recog-ruby#7. Note, the tests on this branch will fail until the recog gem is updated.
```
$ echo "Linksys\nApache\nDNE" | bundle exec ./recog_match --format json xml/http_servers.xml
{"data":"Linksys","match":{"matched":"Linksys Wireless Access Point","os.vendor":"Linksys","os.device":"WAP","hw.vendor":"Linksys","hw.device":"WAP","service.protocol":"http","fingerprint_db":"http_header.server"}}
{"data":"Apache","match":{"matched":"Apache returning no version information","service.vendor":"Apache","service.product":"HTTPD","service.family":"Apache","service.cpe23":"cpe:/a:apache:http_server:-","service.protocol":"http","fingerprint_db":"http_header.server"}} …
```

Add recog_match support for JSON output

---

spec/spec_helper.rb

A temporary fix to restore the rspec progress formatter. `spec/spec_helper.rb` contains a configuration to modify the formatter to documentation when an individual file is specified, however, after the repository split the repo only contains the single spec `spec/lib/fingerprint_self_test_spec.rb`. This change should be undone when another spec is introduced.
Restore expected rspec behavior for previous committers.
* `rake tests`
* `bundle exec rspec`

Temporary fix to restore rspec progress formatter

---

xml/dhcp_vendor_class.xml

Added more fingerprints from observed DHCP vendor_class strings:
* Huawei Android
* Cisco IP Phones
* Cisco Wireless Phones
* Cisco Aironet Wireless Access Points
* Cisco Catalyst Wireless Access Points
* Cisco Integrated Access Points
* Cisco Wireless Controllers
These fingerprints can be used for identifying network devices based on the DHCP fields they advertise
Ran `./bin/recog_verify xml/dhcp_vendor_class.xml`
- New fingerprints

More DHCP-based fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/http_servers.xml

Adds [Talend Restlet Framework](https://restlet.talend.com/) HTTP server fingerprint.
* `rake tests`

Add Talend Restlet Framework fingerprint

---

xml/favicons.xml
xml/html_title.xml
xml/http_servers.xml
xml/tls_jarm.xml

Restores non-capturing groups removed in #381 to fix issues where the anchors will only apply to the immediate value they are next to rather than the sequence of values in an OR match. The tests on the previous PR passed since the examples do not contain any leading or trailing text. Thanks to @dmoinescu-r7 for drawing attention to the issue.
* The current regex `^NETIASPOT Management Console|Konsola zarzdzania NETIASPOT$"` matches the following strings:
```
NETIASPOT Management Console
NETIASPOT Management Consoletest
NETIASPOT Management Console test
Konsola zarzdzania NETIASPOT
testKonsola zarzdzania NETIASPOT
test Konsola zarzdzania NETIASPOT
```
* The corrected regex `^(?:NETIASPOT Management Console|Konsola zarzdzania NETIASPOT)$` only matches the following strings:
```
NETIASPOT …
```

Restore non-capturing groups to fix anchored regex issue

---

identifiers/service_product.txt
xml/http_servers.xml

Adds fingerprint for Python's WSGIServer ([wsgiref.simple_server](https://docs.python.org/3/library/wsgiref.html#module-wsgiref.simple_server)), a simple WSGI HTTP server.
* `rake tests`

Add Python WSGIServer fingerprint

---

identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml
xml/http_servers.xml

Adds [ManageEngine Password Manager Pro](https://www.manageengine.com/products/passwordmanagerpro/) fingerprints
This does not add the hash for the shortcut icon (`<link rel="SHORTCUT ICON" href="/themes/passtrix/V12121/images/ps_ico.ico">`) since that is identical to the `favicon.ico` from ManageEngine Access Manager Plus.
* `/themes/passtrix/V12121/images/ps_ico.ico`:
```
$ file ps_ico.ico
ps_ico.ico: MS Windows icon resource - 6 icons, 256x256 with PNG image data, 256 x 256, 8-bit/color RGBA, non-interlacedPNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced, 32 bits/pixel, -128x-128, 32 bits/pixel
$ md5 ps_ico.ico
MD5 (ps_ico.ico) = 9db18be9073f41227b4fb0c1715ce82d
```
* `/favicon.ico`:
```
favicon.ico: MS Windows icon resource - 2 icons, 16x16, 32 …
```

Add ManageEngine Password Manager Pro fingerprints

---

cpe-remap.yaml
identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds [ManageEngine Access Manager Plus](https://www.manageengine.com/privileged-session-management/) fingerprints
* `/favicon.ico`:
```
favicon.ico: MS Windows icon resource - 6 icons, 256x256 with PNG image data, 256 x 256, 8-bit/color RGBA, non-interlacedPNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced, 32 bits/pixel, -128x-128, 32 bits/pixel
MD5 (favicon.ico) = 9db18be9073f41227b4fb0c1715ce82d
```
* The shortcut icon from ManageEngine Password Manager Pro (`<link rel="SHORTCUT ICON" href="/themes/passtrix/V12121/images/ps_ico.ico">`) is identical to the `favicon.ico` from ManageEngine Access Manager Plus.
* `rake tests`
- New feature (non-breaking …

Add ManageEngine Access Manager Plus fingerprints

---

xml/dhcp_vendor_class.xml

DHCP vendor_class Xerox Printers
Update fingerprint based on new examples, mainly case insensitive matches.
Update for Typ=Printer (uppercase P)
Case insensitive for Mfg, Typ, Mod, Ser and Loc
Support 10 digit serial numbers with example
Added Typ=AIO

DHCP vendor_class Xerox Printer updates

---

xml/dhcp_vendor_class.xml

Poly (formerly Polycom) VVX D230
Fingerprint `Poly-VVX-D230` observed in DHCP traffic
Added example to exercise the fingerprint.
Ran `recog_verify`, `recog_standardize` and `update_cpes.py`

More fingerprints for the Polycom VVX family

---

xml/imap_banners.xml

The `xml/imap_banners.xml` fingerprints were created assuming the `* OK ` portion of the banner was removed, but some of the fingerprint patterns did not account for the possibility of the `[CAPABILITY ...]` string in the banner. This PR adds the missing IMAP CAPABILITY string to the pattern and provides examples. In addition, the "CMU Cyrus IMAP" fingerprint was enhanced to spport banners without `v` prepended to the version. The IMAP CAPABILITY string max match length of 645 was calculated using the longest CAPABILITY string found in the `2022-10-13-1665619548-imaps_993_stage2` Project Sonar study (658 characters) and subtracting the fixed portion of the regex `[CAPABILITY ]` (13 characters).
* `bundle exec ./bin/recog_verify xml/imap_banners.xml`
* `rake tests`
- Bug …

Add missing IMAP CAPABILITY string

---

identifiers/hw_family.txt
xml/dhcp_vendor_class.xml

DHCP fingerprints for Polycom SoundStation IP, as observed in DHCP network traffic.
Ran `recog_verify`, `recog_standardize` and `update_cpes.py`

DHCP fingerprints for Polycom SoundStation IP

---

xml/dhcp_vendor_class.xml

Added DHCP fingerprint for Avaya device
vi_vendor_class string seen in DHCP network traffic: `ccp.avaya.com`
Ran `recog_verify`, `recog_standardize` and `update_cpes.py`

DHCP fingerprint for Avaya device

---

xml/dhcp_vendor_class.xml

New DHCP fingerprints for Aruba sensors, based on data observed inside DHCP packets.
Ran `rake tests`, `recog_verify`, `recog_standardize` and `update_cpes.py`

DHCP fingerprints for Aruba sensors

---

identifiers/vendor.txt
xml/dhcp_vendor_class.xml

Devices whose DHCP identifiers mention only the manufacturer (not the type, model etc):
* Axis
* APC
* Aerohive (part of Extreme Networks)
* Yealink
* Gallagher Group
* Ewon
* Zebra
* Vaddio (part of Legrand AV)
* Cisco
Fingerprints from observed DHCP traffic
Ran `recog_verify`, `recog_standardize` and `update_cpes`
New feature (non-breaking change which adds functionality)

DHCP fingeprints for devices of unknown type/model

---

.github/workflows/ci.yml

Updates the GitHub CI workflow `.github/workflows/ci.yml` to include Ruby `3.1`, and modifies the lower JRuby version making it flexible should any future `9.2.x` versions be released.
To keep CI testing current with new versions.
Changes confirmed by inspecting the GitHub actions run on this branch and PR.

CI Workflow: add Ruby 3.1 and make lower JRuby version flexible

---

.github/workflows/verify.yml
README.md

Updates the Verify workflow and README.md for the Rumble to runZero [rebrand](https://www.runzero.com/blog/introducing-runzero/).
Bring everything up-to-date with external changes.
Checked the GitHub Actions on the PR branch.

Update for Rumble to runZero rebrand

---

identifiers/hw_family.txt
identifiers/hw_product.txt
identifiers/os_family.txt
identifiers/os_product.txt
identifiers/vendor.txt
xml/ftp_banners.xml
xml/snmp_sysdescr.xml

Fixes #503 by correcting the `ZebraNet` vendor to `Zebra`, and making some minor updates to the param of the two fingerprints. The "Zebra ZebraNet Print Server FTP" fingerprint was modified to build `os.product` using the `hw.product` value rather than simply duplicating the value to reflect existing CPE patterns. However, the the `ZBR-#####` values extracted from the banner appear to be more of a product number rather than the product model / name so it is unlikely this will correctly match CPE strings.
* From [ZebraNet II Print Server Firmware – V7.06 (0264A)](https://www.zebra.com/content/dam/zebra_new_ia/en-us/software-printer/firmware/en/release-notes/zebranet-7-06-notes.pdf):
> Note the Product Number that is listed for that print server. In the example below, the Product Number is …

Correct Zebra vendor and minor fingerprint param changes

---

.github/workflows/ci.yml
.github/workflows/verify.yml

Updates the GitHub CI (`.github/workflows/ci.yml`) and Verify (`.github/workflows/verify.yml`) workflow action versions after I observed the following warning when inspecting our action's output.
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
Updates:
* `actions/checkout@v2` to `actions/checkout@v3`
* `actions/cache@v2` to `actions/cache@v3`
* `actions/setup-go@v2` to `actions/setup-go@v3`
Keeping GitHub workflows up-to-date.
Changes confirmed by inspecting the GitHub actions run on this branch and PR.

Update workflow action versions

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [OWASP Zed Attack Proxy](https://www.zaproxy.org/) API web UI fingerprints.
Fingerprinted OWASP ZAP version 2.12.0.
```
favicon.ico: MS Windows icon resource - 6 icons, 256x256 with PNG image data, 256 x 256, 8-bit/color RGBA, non-interlacedPNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced, 32 bits/pixel, -128x-128, 32 bits/pixel
MD5 (favicon.ico) = 1ea465228fa40f5c89f899e51ccc02c9
```
* `rake tests`

Add OWASP Zed Attack Proxy API web UI fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml

Add a fingerprint for [Castopod](https://castopod.org/) based entirely on the favicon
`<link rel="icon" type="image/x-icon" href="/favicon.ico" />`
This was pulled from the current-latest of Castopod, version 1.0.2.
Alas, there were no interesting cookies or `<title>` tags to sample -- Castopod is built using [CodeIgniter](https://codeigniter.com/) and just uses a `ci_session` session cookie without renaming, and `<title>` tags are entirely custom to the content being hosted.
After Twitter changed ownership October of 2022, [Fediverse](https://fediverse.info/) services kind of exploded all over the internet. It would be nice to track them. I suspect there are a lot of new server operators who are diving into the deep end of self-hosted services.
Collected the MD5 of the favicon, hoping …

Castopod favicon fingerprint

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/html_title.xml
xml/http_servers.xml

Adds 2 [darkstat](https://unix4lyfe.org/darkstat/) fingerprints. The vendor name was assembled following from a CPE for another project from the same author (`a:darkhttpd_project:darkhttpd`) since no CPE exists for this project.
* `bundle exec ./bin/recog_verify xml/html_title.xml xml/http_servers.xml`
* `rake tests`

Add darkstat fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/http_servers.xml

Adds a [darkhttpd](https://unix4lyfe.org/darkhttpd/) HTTP server fingerprint.
* `rake tests`

Add darkhttpd HTTP server fingerprint

---

xml/http_servers.xml

Adds [ntopng](https://github.com/ntop/ntopng) HTTP server fingerprints, and many include operating system identification as well.
* `rake tests`

Add ntopng HTTP server fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
spec/lib/fingerprint_self_test_spec.rb
xml/favicons.xml
xml/html_title.xml

Adds two [Bitwarden Server](https://github.com/bitwarden/server) fingerprints. In addition, this modifies the scope of a spec test since it was causing a failure due to the `service.product` parameter value `Server` being considered unhelpful.
Fingerprinted Bitwarden Server Version 2022.12.0.
* `<link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png"/>`
```
$ file favicon-32x32.png
favicon-32x32.png: PNG image data, 32 x 32, 8-bit colormap, non-interlaced
$ md5 favicon-32x32.png
MD5 (favicon-32x32.png) = b071172979419bb7d7b0591409b952dd
```
* `<link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png"/>`
```
$ file favicon-16x16.png
favicon-16x16.png: PNG image data, 16 x 16, 8-bit colormap, non-interlaced
$ md5 favicon-16x16.png
MD5 …
```

Add Bitwarden Server fingerprints 

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Adds two [Vaultwarden](https://github.com/dani-garcia/vaultwarden), unofficial Bitwarden server, fingerprints.
Fingerprinted Vaultwarden server Version 2022.12.0.
* `<link rel="icon" type="image/png" sizes="32x32" href="images/favicon-32x32.png"/>`
```
$ favicon-32x32.png
favicon-32x32.png: PNG image data, 32 x 32, 8-bit gray+alpha, non-interlaced
$ md5 favicon-32x32.png
MD5 (favicon-32x32.png) = 9e8ba456e7e39ea364cc538959813719
```
* `<link rel="icon" type="image/png" sizes="16x16" href="images/favicon-16x16.png"/>`
```
$ file favicon-16x16.png
favicon-16x16.png: PNG image data, 16 x 16, 8-bit gray+alpha, non-interlaced
$ md5 favicon-16x16.png
MD5 (favicon-16x16.png) = 86157069c9574d4c75b907e614d6a521
```
* favicon.ico matches Bitwarden's hash `2f0df01346ace9afb440288feeb5d974` so it was …

Add Vaultwarden fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Adds two [Cacti](https://www.cacti.net/) fingerprints.
Fingerprinted Vaultwarden server Version 2022.12.0.
* `<link href='/cacti/include/themes/modern/images/favicon.ico' rel='shortcut icon'>`
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 8 bits/pixel
MD5 (favicon.ico) = 4f12cccd3c42a4a478f067337fe92794
```
* `<link href='/cacti/include/themes/modern/images/cacti_logo.gif' rel='icon' sizes='96x96'>`
```
$ file cacti_logo.gif
cacti_logo.gif: GIF image data, version 89a, 76 x 121
$ md5 cacti_logo.gif
MD5 (cacti_logo.gif) = 5af2c34a740cf3d0f509d93bcbb41ef6
```
* Note, the file hashes are the same across all of the default themes.
* `rake tests`
- New …

Add Cacti fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/ftp_banners.xml
xml/html_title.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/snmp_sysdescr.xml

Adds four new [Server Technology](https://www.servertech.com/) Sentry Switched device fingerprints, and updates two existing fingerprints. This PR closes #521.
From [Sentry Smart CDU Firmware Revision History](https://cdn10.servertech.com/assets/documents/documents/776/original/smcdu-history.txt):
```
12-03-30	7.0a	smcdu-v70a.bin	First production release
...
Changed the FTP server 220 response code (service ready) login banner
to "220 Sentry Smart CDU <version> FTP server ready.", where
<version> is currently "v7.0a".
Changed the web server identification in HTTP response headers to
"ServerTech-AWS/<version>", where <version> is currently
"v7.0a".  "AWS" is short for Advanced Web Server.
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/ftp_banners.xml …

Add Server Technology Sentry Switched device fingerprints

---

identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds two [ManageEngine ServiceDesk Plus](https://www.manageengine.com/products/service-desk/) fingerprints.
Fingerprinted ServiceDesk Plus 14.1 Build 14103.
* `<link rel="SHORTCUT ICON" href="/images/favicon.ico?14103"/>`
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 32 bits/pixel
MD5 (favicon.ico) = e47c25d118b2c56ce3d7c31786b32a56
```
* `rake tests`

Add ManageEngine ServiceDesk Plus fingerprints

---

cpe-remap.yaml
identifiers/service_product.txt
xml/html_title.xml

Adds one [ManageEngine ServiceDesk Plus MSP](https://www.manageengine.com/products/service-desk-msp/) HTML title fingerprint.
Fingerprinted ServiceDesk Plus MSP 13.0 Build 13002.
* `<link rel="SHORTCUT ICON" href="/images/favicon.ico?13002"/>`
```
favicon.ico: MS Windows icon resource - 3 icons, 48x48, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = 3691a7e782c685b44023c9c4e3f3a31c
```
No fingerprint was created for the favicon.ico at this time since it appeared to match some other products.
* `rake tests`

Add ManageEngine ServiceDesk Plus MSP HTML title fingerprint

---

cpe-remap.yaml
identifiers/service_product.txt
xml/http_cookies.xml

Adds one [ManageEngine Active Directory 360 (AD360)](https://www.manageengine.com/active-directory-360/index.html) HTTP cookie fingerprint.
* `bundle exec ./bin/recog_verify xml/http_cookies.xml`
* `rake tests`

Add ManageEngine Active Directory 360 (AD360) HTTP cookie fingerprint

---

cpe-remap.yaml
identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml
xml/http_cookies.xml

Adds three [ManageEngine ADManager Plus](https://www.manageengine.com/products/ad-manager/) fingerprints.
Fingerprinted ADManager Plus version 7.1.0 build 7180.
* `<link rel="icon" type="image/x-icon" href="images/favicon.ico"/>`
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 32 bits/pixel
MD5 (favicon.ico) = 6d14f0aa6a61fe4780b94b42eed19e83
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/html_title.xml xml/http_cookies.xml`
* `rake tests`

Add ManageEngine ADManager Plus fingerprints

---

cpe-remap.yaml
identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml

Adds three new [Control Web Panel](https://control-webpanel.com/) (formerly CentOS Web Panel) fingerprints.
Fingerprinted CWP7 version 0.9.8.1148.
* `<link rel="icon" href="design/img/ico/favicon.ico" type="image/png">`
* `<link rel="icon" href="/login/cwp_theme/original/img/ico/favicon.ico" type="image/png">`
```
favicon.ico: MS Windows icon resource - 2 icons, 16x16, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = 6b774f15b254a3d1548db63b6f411150
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/html_title.xml xml/http_cookies.xml`
* `rake tests`

Add Control Web Panel (formerly CentOS Web Panel) fingerprints

---

xml/dhcp_vendor_class.xml

Add Cambium Wireless Access Point to dhcp_vendor_class
* `./bin/recog_verify xml/dhcp_vendor_class.xml`
* `rake tests`

Add Cambium Wireless Access Point to dhcp_vendor_class

---

xml/http_cookies.xml

Adds another [ManageEngine ADSelfService Plus](https://www.manageengine.com/products/self-service-password/) cookie fingerprint.
Fingerprinted ADSelfService Plus version 6.2 build 6215.
* `bundle exec ./bin/recog_verify xml/http_cookies.xml`
* `rake tests`

Add another ManageEngine ADSelfService Plus cookie fingerprint

---

cpe-remap.yaml
identifiers/service_product.txt
xml/favicons.xml
xml/http_cookies.xml

Adds 2 [ManageEngine Analytics Plus](https://www.manageengine.com/analytics-plus/) fingerprints.
Fingerprinted Analytics Plus version 5.1.2, build number 5121.
```
favicon.ico: MS Windows icon resource - 3 icons, 48x48, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = 1b476eae7d17844198fa494251ba910a
```
* `bundle exec ./bin/recog_verify xml/favicons.xml xml/http_cookies.xml`
* `rake tests`

Add ManageEngine Analytics Plus fingerprints

---

cpe-remap.yaml
identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [ManageEngine AssetExplorer](https://www.manageengine.com/products/asset-explorer/) fingerprints.
Fingerprinted AssetExplorer version 6.9, build 6987.
* `<link rel="SHORTCUT ICON" href="images/favicon.ico"/>`
```
favicon.ico: MS Windows icon resource - 1 icon, 48x48, 32 bits/pixel
MD5 (favicon.ico) = ae9449edb0067aa8c2c292acbe93da6a
```
* `favicon.ico` (alternative from unknown version)
```
favicon.ico: MS Windows icon resource - 4 icons, 48x48, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = a79bce1c22f081b0d1e38b142827a0e8
```
* `rake tests`

Add ManageEngine AssetExplorer fingerprints

---

identifiers/hw_product.txt
xml/dhcp_vendor_class.xml

Added Avaya E129 IP Phone to dhcp_vendor_class
Added E129 to hw_product.tx
Extend coverage
./bin/recog_verify xml/dhcp_vendor_class.xml 
rake tests

Add Avaya E129 to dhcp_vendor_class

---

cpe-remap.yaml
identifiers/service_product.txt
xml/html_title.xml

Add [ManageEngine Endpoint Central (formerly Desktop Central)](https://www.manageengine.com/products/desktop-central/) HTML title fingerprint. Note, the CPE remapping should be revisited when NVD updates the CPE entry for the product name change.
* `rake tests`

Add ManageEngine Endpoint Central HTML title fingerprint

---

cpe-remap.yaml
identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [ManageEngine SupportCenter Plus](https://www.manageengine.com/products/support-center/) fingerprints.
Fingerprinted SupportCenter Plus version 14.0, build 14000.
* `<link rel="shortcut icon" href="/images/favicon.ico?14000">`
```
favicon.ico: PNG image data, 48 x 48, 8-bit/color RGBA, non-interlaced
MD5 (favicon.ico) = 4098755981824f02879b05ea2cc4da14
```
* `favicon.ico` (alternative from unknown version)
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 4 bits/pixel
MD5 (favicon.ico) = f8affc42a31d3c2fa044b882b4656bc9
```
* `rake tests`

Add ManageEngine SupportCenter Plus fingerprints

---

xml/favicons.xml

Adds [Atlassian Jira](https://www.atlassian.com/software/jira) v9.6.0 favicon fingerprint.
Fingerprinted Jira version 9.6.0.
* `<link rel="shortcut icon" href="/s/y7oy14/960000/1dlckms/_/images/fav-jsw.png">`
```
$ file fav-jsw.png
fav-jsw.png: PNG image data, 128 x 128, 8-bit/color RGBA, non-interlaced
$ md5 fav-jsw.png
MD5 (fav-jsw.png) = eadf13e6cac2efef4f0565e171f90953
```
* `rake tests`

Add Atlassian Jira v9.6.0 favicon fingerprint

---

identifiers/service_product.txt
xml/favicons.xml

Adds [Atlassian Jira Service Management](https://www.atlassian.com/software/jira/service-management) favicon fingerprint.
Fingerprinted JIRA Service Management Application version 5.6.0.
* `<link rel="shortcut icon" href="/s/-8ncmrq/960000/1dlckms/_/images/fav-jsd.png">`
```
$ file fav-jsd.png
fav-jsd.png: PNG image data, 128 x 128, 8-bit/color RGBA, non-interlaced
$ md5 fav-jsd.png
MD5 (fav-jsd.png) = 2fa69f2bc9174ffc21fc3c7925da6862
```
* `rake tests`

Add Atlassian Jira Service Management favicon fingerprint

---

xml/dhcp_vendor_class.xml

Added LG TV DHCP vendor class fingerprint
This covers a variety of devices that are described by LG as 
TV, Commercial TV, Digital Signage
Details from
https://www.lg.com/ca_en/support/product-help/CT20098005-20150585049620
Selected webOS as all LG TV appear to be webOS
Extends coverage 
rake tests

Added LG TV to dhcp_vendor_class

---

xml/dhcp_vendor_class.xml

Added Zebra Label Printer to dhcp_vendor_class
New fingerprint for improved coverage
rake tests

Add Zebra Label Printer to dhcp_vendor_class

---

identifiers/hw_product.txt
xml/dhcp_vendor_class.xml

Added ShoreTel IP Phone to dhcp_vendor_class
Extend coverage
rake tests

Added ShoreTel IP Phone to dhcp_vendor_class

---

xml/dhcp_vendor_class.xml
xml/dns_versionbind.xml
xml/http_wwwauth.xml
xml/imap_banners.xml
xml/smb_native_os.xml
xml/smtp_banners.xml
xml/snmp_sysdescr.xml
xml/ssh_banners.xml

This PR moves the inline flag `(?i)` (case insensitivity)  to the beginning of the regex. In Python this flags has global meaning and use of it anywhere other than the start of the pattern is deprecated. This does not change the function of this flag in current patterns for other languages.
See previous work in https://github.com/rapid7/recog/pull/367
This was caught by internal testing in `recog-go` and the fixes are required in order for us to implement and test the changes from the following PRs into `recog-go`:
- https://github.com/rapid7/recog-ruby/pull/12
- https://github.com/rapid7/recog/pull/547
`ruby bin/recog_verify xml/*.xml | grep -v WARN | grep -v SUMMARY`
- Content

Cross language compatibility: case insensitivity flag

---

identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [ConnectWise R1Soft Server Backup Manager (SBM)](https://www.connectwise.com/platform/integrations/business-efficiency/r1soft) fingerprints.
```
favicon.ico: MS Windows icon resource - 4 icons, 48x48, 32 bits/pixel, 32x32, 32 bits/pixel
MD5 (favicon.ico) = f46baa8367ecf994a9c50ce7fb89f483
```
* `rake tests`

Add ConnectWise R1Soft Server Backup Manager fingerprints

---

xml/favicons.xml

Add latest favicon fingerprint hashes for drupal 9.2 plus
Add latest favicon fingerprint hashes for drupal 9.2 plus
```
$ curl --silent https://raw.githubusercontent.com/drupal/drupal/10.1.x/core/misc/favicon.ico | md5sum | awk '{ print $1 }' | bin/recog_match xml/favicons.xml -
MATCH: {"matched"=>"Drupal CMS", "service.vendor"=>"Drupal", "service.product"=>"CMS", "service.certainty"=>"0.5", "service.cpe23"=>"cpe:/a:drupal:drupal:-", "service.protocol"=>"", "fingerprint_db"=>"favicon.md5", "data"=>"fe22dd2bb09daccf58256611ac491469"}
```

Add favicon hash for drupal 9.2 plus

---

Gemfile
README.md
bin/recog_standardize
features/data/successful_tests.xml
features/verify.feature

This PR mirrors README changes from https://github.com/rapid7/recog-ruby/pull/12
Please see that PR for discussion.
it also prevents the `_tmp.` attributes from being added to the `identifiers/fields.txt` file.
NOTE: Tests involving `features/data/successful_tests.xml` and the `recog-ruby` implementation SHOULD fail until that PR is landed.

mirror doc changes from recog-ruby

---

README.md

Updates `README.md` testing matches examples to set the grep color to `never` to avoid possible issues.
I discovered having grep aliased to `grep --color=always` caused some confusion when experimenting with the new examples under the "Testing matches" section added in #557.
```
$ echo 'laravel_session=eyJ...etc..etc...%3D; expires=Mon, 13-Mar-2023 16:48:58 GMT; Max-Age=7200; path=/; httponly; samesite=lax' | bin/recog_match xml/http_cookies.xml -
MATCH: {"matched"=>"Laravel PHP web application framework", "service.vendor"=>"Laravel", "service.product"=>"Laravel", "service.cpe23"=>"cpe:/a:laravel:laravel:-", "service.protocol"=>"http", "fingerprint_db"=>"http_header.cookie", "data"=>"laravel_session=eyJ...etc..etc...%3D; expires=Mon, 13-Mar-2023 16:48:58 GMT; Max-Age=7200; path=/; …
```

Update README.md testing matches to set grep color to never

---

cpe-remap.yaml
identifiers/hw_product.txt
identifiers/os_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Adds 5 fingerprints for FatPipe Networks MPVPN, IPVPN, WARP and SDWAN products.
Fingerprinted various product versions (7.1.2r186p12, 9.1.2r156, 9.1.2r161p26, etc.)
* `/fpui/img/favicon.ico` (login)
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16, 16 colors, 4 bits/pixel
MD5 (favicon.ico) = eddb2b697c8c3dab5a9572de564976d1
```
* `favicon.ico` (remote configuration)
```
favicon.ico: MS Windows icon resource - 1 icon, 16x16
MD5 (favicon.ico) = b0f000f8041a6f1d2c366972b1dbad69
```
* `rake tests`

Add FatPipe Networks MPVPN, IPVPN, WARP, SDWAN fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/html_title.xml
xml/http_servers.xml
xml/http_wwwauth.xml

Add Transmission

---

identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [PaperCut](https://www.papercut.com/) MF and NG fingerprints that only emit the service vendor.
Fingerprinted PaperCut MF builds 54736, 57908, 63915, 65190 and 65997, and PaperCut NG build 59505.
* `/images/icons3/favicon.ico`
```
favicon.ico: MS Windows icon resource - 6 icons, 256x256 with PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced, 32 bits/pixel, -128x-128, 32 bits/pixel
MD5 (favicon.ico) = 4764ad78b4c0d93bc48d4d0df3b36c7e
```
Fingerprinted PaperCut MF build 47777.
* `/images/icons3/favicon.ico`
```
favicon.ico: MS Windows icon resource - 5 icons, 64x64, 32 bits/pixel, 48x48, 32 bits/pixel
MD5 (favicon.ico) = 8d8030454ec1d7f96c8fdf670d4eb3c6
```
* `bundle exec …

Add PaperCut MF and NG vendor only fingerprints

---

identifiers/service_product.txt
xml/favicons.xml
xml/html_title.xml

Adds 2 [Apache Superset](https://superset.apache.org/) fingerprints.
Fingerprinted Apache Superset version 2.1.0.
* `favicon.png`
```
$ file favicon.png
favicon.png: PNG image data, 260 x 260, 8-bit/color RGBA, non-interlaced
$ md5 favicon.png
MD5 (favicon.png) = 0629ce6bd8a86ff6b5dbb2a24c040849
```
* `rake tests`

Add Apache Superset fingerprints

---

xml/http_servers.xml

Corrects the `param` order in one of the Transmission fingerprints added in #568.
Maintain consistent `param` order
* `rake tests`

Correct param order in Transmission fingerprint

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml

Add `title` and `favicon` fingerprints for Jellyseerr
https://github.com/Fallenbagel/jellyseerr is getting popular, let's add it
On my LAN.

Add Jellyseerr fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_wwwauth.xml

Add Sonarr/Radarr/Prowlarr
On my LAN

Add Sonarr/Radarr/Prowlarr

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_servers.xml

Adds 3 [fast reverse proxy (frp)](https://github.com/fatedier/frp) fingerprints.
Fingerprinted frp version 0.48.0.
```
favicon.ico: MS Windows icon resource - 1 icon, 48x48, 32 bits/pixel
MD5 (favicon.ico) = 57801ef5135f6a6e8ea69baef85f8607
```
* `rake tests`

Add fast reverse proxy (frp) fingerprints

---

.github/workflows/ci.yml

Updates the GitHub CI workflow `.github/workflows/ci.yml` to pin the upper JRuby version to `9.4.2` as a temporary workaround for Nokogiri method redefined warnings causing test failures.
```
/home/runner/work/recog/recog/vendor/bundle/jruby/3.1.0/gems/nokogiri-1.15.2-java/lib/nokogiri/xml/node.rb:1007: warning: method redefined; discarding old attr
(RSpec::Expectations::ExpectationNotMetError)
```
The source of the issue appears to be related to jruby/jruby#7183.
Unblock CI testing issue.
* Inspect test results in this PR

CI Workflow: pin upper JRuby version to 9.4.2 as workaround for test failures

---

cpe-remap.yaml
identifiers/hw_product.txt
identifiers/os_family.txt
identifiers/os_product.txt
identifiers/service_product.txt
identifiers/vendor.txt
update_cpes.py
xml/apache_modules.xml
xml/favicons.xml
xml/ftp_banners.xml
xml/html_title.xml
xml/http_cookies.xml
xml/http_servers.xml
xml/http_wwwauth.xml
xml/mdns_device-info_txt.xml
xml/sip_banners.xml
xml/sip_user_agents.xml
xml/snmp_sysdescr.xml
xml/telnet_banners.xml
xml/tls_jarm.xml
xml/x11_banners.xml
xml/x509_issuers.xml
xml/x509_subjects.xml

Updates `update_cpes.py` to make CPE string handling more consistent throughout the script and remap process, and implement CPE URI binding format percent-encoding. Corrects `service`, `os` and `hw` parameters and updates CPE values.
* `o:cisco:adaptive_security_appliance_software` deprecated by `a:cisco:adaptive_security_appliance_software` on 2022-05-26
* This seems incorrect since Cisco's states "Cisco Adaptive Security Appliance (ASA) Software is the core operating system for the Cisco ASA Family."[^1]
* `h:cisco:ios` deprecated by `o:cisco:ios` on 2022-09-02
* `a:cisco:ios` deprecated by `o:cisco:ios` on 2021-10-06
* `a:varnish-cache:varnish_cache` deprecated by `a:varnish_cache_project:varnish_cache` on 2022-08-02
* `a:varnish-cache:varnish` deprecated by …

Enhance CPE update script and update CPE values

---

identifiers/service_product.txt
xml/http_cookies.xml
xml/ssh_banners.xml

Adds 2 [Progress MOVEit Transfer](https://www.progress.com/moveit) fingerprints.
Fingerprinted unknown versions of MOVEit Transfer.
The favicon fingerprint was not added at this time since it appears to only be the Progress logo.
```
progress-moveit-transfer-favicon.ico: MS Windows icon resource - 8 icons, 256x256, 32 bits/pixel, 16x16, 32 bits/pixel
MD5 (favicon.ico) = 9dffe2772e6553e2bb480dde2fe0c4a6
```
* `bundle exec ./bin/recog_verify xml/http_cookies.xml xml/ssh_banners.xml`
* `rake tests`

Add Progress MOVEit Transfer fingerprints

---

identifiers/service_product.txt
identifiers/vendor.txt
xml/favicons.xml
xml/html_title.xml
xml/http_cookies.xml

Adds 3 [Roundcube Webmail](https://roundcube.net/) fingerprints.
Fingerprinted Roundcube Webmail versions 1.6.1, 1.5.0, 1.4.13 and 1.4.12.
* `skins/elastic/images/favicon.ico` ([1.6.1](https://github.com/roundcube/roundcubemail/releases/tag/1.6.1))
```
$ file roundcubemail-1.6.1/skins/elastic/images/favicon.ico
roundcubemail-1.6.1/skins/elastic/images/favicon.ico: MS Windows icon resource - 1 icon, 64x64, 32 bits/pixel
$ md5 roundcubemail-1.6.1/skins/elastic/images/favicon.ico
MD5 (roundcubemail-1.6.1/skins/elastic/images/favicon.ico) = 924a68d347c80d0e502157e83812bb23
```
* `skins/elastic/images/favicon.ico` ([1.5.0](https://github.com/roundcube/roundcubemail/releases/tag/1.5.0))
* `skins/classic/images/favicon.ico` ([1.5.0](https://github.com/roundcube/roundcubemail/releases/tag/1.5.0)) …

Add Roundcube Webmail fingerprints

---

spec/lib/fingerprint_self_test_spec.rb

Fix non-deterministic test order when running tests. A test failure on CI outputs an error with the reproducible test steps:
```
Failed examples:
rspec './spec/lib/fingerprint_self_test_spec.rb[1:29:120:3]' # Recog::DB#http_cookies.xml (?-mix:^(__Host-)?(nc_sameSiteCookiestrict|nc_sameSiteCookielax|oc_sessionPassphrase)=) uses capturing regular expressions properly
```
However - the test may not actually for a developer's local dev env, as `Dir` is used without an explicit sort:
> Overview. 'Dir` and `Dir. glob(…)` do not make any guarantees about the order in which files are returned. The final order is determined by the operating system and file system.
Developers want consistency between CI and local testing env
CI Passes

Fix non-deterministic test order

---

xml/http_xpoweredby.xml

Add X-Powered-By fingerprinting
A lot of software are ~~bragging~~ advertising their presence via the `X-Powered-By` header.
On my lan
This should close #574

Add X-Powered-By fingerprinting

---

bin/recog_cleanup
xml/favicons.xml
xml/telnet_banners.xml

Fix rubocop formatting complaints causing CI tests to fail.
- Tested locally

Fix rubocop formatting complaints

---

xml/favicons.xml

md5 collision is highly unlikely, and it's the only (as far as I know) product with this favicon.

Bump the certainty for AdGuard

---

xml/x509_subjects.xml

Add a fingerprint for the freebox' x509_subjects
It wasn't there
On my lan

Add a fingerprint for the freebox' x509_subjects

---

xml/sip_user_agents.xml

The Regex changed suffers from an exponential degree of ambiguity.
As a result it is trivial to provide an input string which takes an incredibly long time to match (due to exponential growth by length of input string).
Related: https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS
---
Here's an example of how to show this with code.
Tested on Java 8 which exhibits the issue. Tested on Java 11 which did not present the issue, some research online suggests that Java 11 featured some improvements to try to mitigate this. Either way, since this is a collection of patterns which are language agnostic we should probably not support patterns like this.
```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
* Tests the runtime of matching a …
```

Fix regex which has exponential degree of ambiguity

---

identifiers/hw_family.txt
identifiers/os_family.txt
identifiers/os_product.txt
xml/snmp_sysdescr.xml

Added `fingerprints` for:
- Meraki MX Cloud-Managed Security and SD-WAN</description>
- Meraki MR Cloud-Managed Wi-Fi Access Points</description>
- Meraki MS Cloud-Managed Network Switches</description>
Coverage for Cisco Meraki devices is needed. 
Tested locally if Meraki devices are detected during the Asset Scan.

Added fingerprints for Cisco Meraki Mx Ms and Mr

---

xml/snmp_sysdescr.xml

Added start anchor to Meraki fingerprints
This is to keep the newly added fingerprints in line with the project-wide standard.
Tested if the original test cases are passing with:` bin/recog_verify xml/snmp_sysdescr.xml`

Added start anchor to Meraki fingerprints

---

.github/workflows/ci.yml
.github/workflows/rubocop.yml
.github/workflows/verify.yml

This PR upversions `actions/checkout` from v3 to v4 in this repo's Github actions.
On the Github actions, like here https://github.com/rapid7/recog/actions/runs/8713056113 there are deprecation warnings. v3 of the action used Node.js 16, which is deprecated by Github. v4 changes this to Node.js 20.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- Example of the errors appearing: https://github.com/rapid7/recog/actions/runs/8713056113
- Example of the errors cleared: …

upversion actions/checkout

---

Gemfile
bin/recog_cleanup

Fix CI build failure when running in Ruby 2.7.5 docker environment:
```
docker run -it -w $(pwd) -v $(pwd):$(pwd) --rm ruby:2.7.5 /bin/sh
```
Before:
```
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
ffi-1.17.0-x86_64-linux-musl requires rubygems version >= 3.3.22, which is incompatible with the current version, 3.1.6
```
After:
```
...
Bundle complete! 12 Gemfile dependencies, 49 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
Fix CI failing on ffi dependency issues
CI passes
- Bug fix

Pin ffi gem version in Gemfile

---

xml/snmp_sysdescr.xml

Added Fingerprinting for Ivanti Pulse Secure 
After rebranding Pulse Secure to Ivanti, the vendor hid information about subsequent versions and their hashes, we had to come up with a new approach for retrieving information about the version of the product, this approach uses SNMP  to collect version information.
Ran nexpose with these arguments on vCenter:
```
./run.sh nexpose -Dr7.deploy.local.recog=true -Drecog.dir=~/rapid7/recog
```
And then scanned an existing Ivanti Connect Secure scan target.
Scan results before change:
Scan results after change:
- New feature, Added new fingerprinting for Ivanti Connect Secure

VC-2316 Add fingerprinting for ivanti pulse secure

---

xml/http_wwwauth.xml

I am extending the D-Link record to also have some trivial information about the OS.
A downstream consumer of wwwauth is unable to work with records that have only information about HW. At least trivial information about the os.vendor is needed.
I am intentionally leaving the `hw.product` in place, so that the implementation is backward compatible.

extend D-Link DCS wwwauth record

---

identifiers/os_family.txt
identifiers/os_product.txt
xml/sip_banners.xml

Updated sip-banner record for Cisco Telepresence to reflect the current product naming, vendor, family. Make regex more strict to match only versions starting with X and TC. 
SIP protocol example:
SIP/2.0 403 Forbidden
Via: SIP/2.0/UDP nm;branch=foo;received=224.85.86.107;rport=26810;ingress-zone=DefaultZone
Call-ID: 50000
CSeq: 42 OPTIONS
From: <sip:nm@nm>;tag=root
To: <sip:nm2@nm2>;tag=dba04991a2a1090f
Server: TANDBERG/4145 (X15.0.3)
Tested with bin/recog_verify

Update sip_banners record for Cisco Telepresence

---

identifiers/os_product.txt
xml/sip_banners.xml

After additional research into the TelePresence product line I think we should distinguish different OSes based on the version string. I was able to determine, that
- `X prefix` marks the Expressway / Video Communication Server 
- https://www.cisco.com/c/en/us/support/unified-communications/expressway-series/products-release-notes-list.html
- https://www.cisco.com/c/en/us/support/unified-communications/telepresence-video-communication-server-vcs/products-release-notes-list.html 
- `XC prefix` marks the Telepresence Conductor - https://www.cisco.com/web/software/280886992/128362/TelePresence-Conductor-Release-Notes-XC4-0.pdf
- `ce prefix` marks the Collaboration Endpoint, which is now rebranded to RoomOS. 
- `TC/TCNC prefix` are historical releases, I am reverting the change we did for …

Distinguish different Telepresence products

---

identifiers/os_product.txt
xml/snmp_sysdescr.xml

Add fingerprinting for Cisco TelePresence Cisco Collaboration Endpoint. Add new record to recog snmp. Update regex to only detect versions starting with ce.

Add Cisco CE fingerprinter

---

identifiers/os_family.txt
identifiers/os_product.txt
xml/snmp_sysdescr.xml

Add Aruba OS 8/10/CX SNMP fingerprinters.
SIP examples provided

add SNMP fingerprinters for ArubaOS 8/10/CX

---

.github/workflows/ci.yml

This PR pins the ubuntu version to `ubuntu-22.04` in the Github Action CI pipeline, as `jruby-9.2` and `'jruby-9.4.2` versions are no longer supported on `ubuntu-latest` (currently `ubuntu-24.10`).
Fixes failing PR checks i.e. https://github.com/rapid7/recog/actions/runs/12926372714/job/36055534595?pr=635

Pin ubuntu version to 22.04 in ci

---

identifiers/os_product.txt
xml/snmp_sysdescr.xml

Updated SNMP fingerprinters for Aruba AOS-CX and Aruba AOS-S.
These updates increase accuracy of the SNMP fingerprinters of Aruba AOS-CX and Aruba AOS-S. The update of AOS-CX aim to prevent the fingerprinter pattern matching with another operating system The update Aruba AOS-S makes the fingeprinter more general and applicable for other hardware models.
Test scan performed:

Update of the fingerprinters for Aruba AOS-CX and Aruba AOS-S

---

xml/snmp_sysdescr.xml

The purpose of this change is to improve a coverage for Aruba AOS-CX SNMP fingerprinter. The current coverage is missing models with a multiple word model specification. Additional test strings were added and the regular expression for SNMP fingerprinter was updated.
This change improves the coverage of Aruba AOS-CX switches to models with multiple word naming.
Additional controls strings where added next to the existing one. The regular expressions was tested with other Aruba test strings to prevent confusion with another switch model.

Fix of Aruba AOS-CX SNMP fingerprinter

---

xml/mysql_banners.xml

Added banner for MariaDB on Ubuntu20 
Installed the required MariaDB version on the VM, ran the scan. 
Result :  `[mysql.banners] Matching against banner: 11.8.2-MariaDB-ubu2204`

Added banner for MariaDB 
